# Generated by Django 5.2.3 on 2025-09-05 03:53

import django.db.models.deletion
from django.conf import settings
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cruceros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Administracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costos_totales', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ganancias_totales', models.DecimalField(decimal_places=2, max_digits=12)),
                ('presupuesto_estimado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_combustible', models.DecimalField(decimal_places=2, max_digits=10)),
                ('num_pasajeros_actual', models.PositiveIntegerField()),
                ('num_empleados_actual', models.PositiveIntegerField()),
                ('crucero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finanzas', to='cruceros.crucero')),
            ],
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('leida', models.BooleanField(default=False)),
                ('administracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='administracion.administracion')),
            ],
        ),
        migrations.CreateModel(
            name='Habitaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('indivual', 'Individual'), ('double', 'Doble'), ('triple', 'Triple'), ('quadruple', 'Cuadruple'), ('penthouse', 'Penthouse'), ('suite', 'Suite'), ('ship_crew', 'De tripulación')], max_length=20)),
                ('id_room', models.PositiveIntegerField()),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('ubicacion', models.CharField(max_length=25)),
                ('estado', models.CharField(choices=[('free', 'Libre'), ('reserved', 'Reservada'), ('occupied', 'Ocupada'), ('maintenance', 'Mantenimiento')], default='free', max_length=20)),
                ('espacio_area', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('nombre_usuario', models.CharField(default='free', max_length=25)),
                ('capacidad', models.PositiveIntegerField()),
                ('vista_mar', models.BooleanField(default=False)),
                ('ultimo_mantenimiento', models.DateField()),
                ('proximo_mantenimiento', models.DateField()),
                ('costo_final', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('cubierta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='habitaciones', to='administracion.cubierta')),
            ],
            options={
                'verbose_name': 'Habitación',
                'verbose_name_plural': 'Habitaciones',
            },
        ),
        migrations.CreateModel(
            name='Cubierta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('numero', models.PositiveIntegerField()),
                ('area_disponible', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('area_restante', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('crucero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cubierta', to='cruceros.crucero')),
            ],
            options={
                'verbose_name': 'Cubierta',
                'verbose_name_plural': 'Cubiertas',
            },
        ),
    ]
