# Generated by Django 5.2.6 on 2025-09-11 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cruceros", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Modulo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50, unique=True)),
                ("descripcion", models.TextField(blank=True)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Módulo",
                "verbose_name_plural": "Módulos",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="UsuarioRol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_asignacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_expiracion", models.DateTimeField(blank=True, null=True)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Rol de Usuario",
                "verbose_name_plural": "Roles de Usuarios",
                "ordering": ["-fecha_asignacion"],
            },
        ),
        migrations.CreateModel(
            name="Administracion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "costos_totales",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "ganancias_totales",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "presupuesto_estimado",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "precio_combustible",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("num_pasajeros_actual", models.PositiveIntegerField()),
                ("num_empleados_actual", models.PositiveIntegerField()),
                (
                    "crucero",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="finanzas",
                        to="cruceros.crucero",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Alerta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mensaje", models.CharField(max_length=255)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("leida", models.BooleanField(default=False)),
                (
                    "administracion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alertas",
                        to="administracion.administracion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("admin", "Administrador"),
                            ("editor", "Editor"),
                            ("lector", "Lector"),
                            ("especialista", "Especialista"),
                        ],
                        max_length=20,
                    ),
                ),
                ("descripcion", models.TextField(blank=True)),
                (
                    "permisos",
                    models.JSONField(
                        default=dict, help_text="Permisos específicos del rol"
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "modulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="administracion.modulo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rol",
                "verbose_name_plural": "Roles",
                "ordering": ["modulo", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="SolicitudCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=12)),
                ("descripcion", models.TextField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("approved", "Aprobada"),
                            ("rejected", "Rechazada"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("razon_rechazo", models.TextField(blank=True, null=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "crucero",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cruceros.crucero",
                    ),
                ),
            ],
        ),
    ]
