# Generated by Django 5.2.3 on 2025-09-12 04:23

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
        ('cruceros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administracion',
            options={'verbose_name': 'Finanzas', 'verbose_name_plural': 'Finanzas'},
        ),
        migrations.RemoveField(
            model_name='alerta',
            name='administracion',
        ),
        migrations.AddField(
            model_name='alerta',
            name='crucero',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='administracion.administracion'),
        ),
        migrations.AlterField(
            model_name='administracion',
            name='precio_combustible',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='administracion',
            name='presupuesto_estimado',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='habitaciones',
            name='aumento_ubicacion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='habitaciones',
            name='aumento_vista_mar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='habitaciones',
            name='costo_extra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.CreateModel(
            name='Instalaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('restaurant', 'Restaurante'), ('bar', 'Bar'), ('pool', 'Piscina'), ('theater', 'Teatro'), ('lobby', 'Recepción'), ('warehouse', 'Almacén'), ('nursery', 'Enfermería'), ('employee_restroom', 'Área de empleados'), ('event_room', 'Espacio de eventos'), ('navigation_bridge', 'Puente de navegación')], max_length=20)),
                ('capacidad', models.PositiveIntegerField()),
                ('espacio_area', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('id_instalacion', models.PositiveIntegerField()),
                ('ubicacion', models.CharField(max_length=25)),
                ('estado', models.CharField(choices=[('active', 'Activa'), ('reserved', 'Reservada'), ('occupied', 'Ocupada'), ('maintenance', 'En mantenimiento')], default='active', max_length=20)),
                ('ultimo_mantenimiento', models.DateField()),
                ('proximo_mantenimiento', models.DateField()),
                ('cubierta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instalaciones', to='administracion.cubierta')),
            ],
            options={
                'verbose_name': 'Instalación',
                'verbose_name_plural': 'Instalaciones',
            },
        ),
        migrations.RenameModel(
            old_name='Administracion',
            new_name='Dashboard',
        ),
    ]
