# Generated by Django 4.2.7 on 2025-09-06 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_solicitudcompra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administracion',
            name='costos_totales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='administracion',
            name='ganancias_totales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='administracion',
            name='num_empleados_actual',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='administracion',
            name='num_pasajeros_actual',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='administracion',
            name='precio_combustible',
            field=models.DecimalField(decimal_places=2, default=2.5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='administracion',
            name='presupuesto_estimado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
