# Generated by Django 5.2.4 on 2025-09-13 04:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crucero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Crucero')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Crucero',
                'verbose_name_plural': 'Cruceros',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Plato')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad en Stock')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio')),
                ('included', models.BooleanField(default=True, verbose_name='Incluido en el Paquete')),
                ('min_stock_alert', models.IntegerField(default=10, verbose_name='Alerta de Stock Mínimo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Item del Menú',
                'verbose_name_plural': 'Items del Menú',
            },
        ),
        migrations.CreateModel(
            name='ConsumptionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cruise_day', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)], verbose_name='Día del Crucero')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Total')),
                ('is_included', models.BooleanField(verbose_name='Incluido en el Paquete')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Consumo')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurante.menuitem', verbose_name='Item del Menú')),
            ],
            options={
                'verbose_name': 'Registro de Consumo',
                'verbose_name_plural': 'Registros de Consumo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Restaurante')),
                ('type', models.CharField(choices=[('buffet', 'Buffet'), ('principal', 'Restaurante Principal'), ('tematico', 'Restaurante Temático'), ('roomservice', 'Room Service')], max_length=20, verbose_name='Tipo')),
                ('capacity', models.IntegerField(default=100, verbose_name='Capacidad')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crucero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurante.crucero', verbose_name='Crucero')),
            ],
            options={
                'verbose_name': 'Restaurante',
                'verbose_name_plural': 'Restaurantes',
            },
        ),
        migrations.AddField(
            model_name='menuitem',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurante.restaurante', verbose_name='Restaurante'),
        ),
        migrations.CreateModel(
            name='MaintenanceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('cocina', 'Cocina'), ('comedor', 'Comedor'), ('bar', 'Bar'), ('almacen', 'Almacén'), ('equipos', 'Equipos'), ('refrigeracion', 'Refrigeración'), ('limpieza', 'Limpieza')], max_length=20, verbose_name='Área')),
                ('description', models.TextField(verbose_name='Descripción del Problema')),
                ('priority', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], max_length=10, verbose_name='Prioridad')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=15, verbose_name='Estado')),
                ('reported_by', models.CharField(max_length=100, verbose_name='Reportado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Reporte')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Completado')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurante.restaurante', verbose_name='Restaurante')),
            ],
            options={
                'verbose_name': 'Item de Mantenimiento',
                'verbose_name_plural': 'Items de Mantenimiento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('position', models.CharField(choices=[('executive', 'Chef Ejecutivo'), ('chef-partie', 'Jefe de estación'), ('maitre-d', 'Jefe de comedor'), ('bartender', 'Bartender'), ('pastelero', 'Pastelero'), ('cocinero', 'Cocinero'), ('auxiliar', 'Auxiliares de cocina'), ('mesero', 'Mesero'), ('jefe-mesero', 'Jefe de meseros')], max_length=20, verbose_name='Cargo')),
                ('shift', models.CharField(choices=[('mañana', 'Mañana (6:00-14:00)'), ('tarde', 'Tarde (14:00-22:00)'), ('noche', 'Noche (22:00-6:00)')], max_length=10, verbose_name='Turno')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('hire_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Contratación')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurante.restaurante', verbose_name='Restaurante')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
    ]
