# Generated by Django 4.2.24 on 2025-09-04 03:04

import apps.cruceros.Services.fecha_general
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cruceros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.IntegerField()),
                ('cantidad_productos', models.PositiveIntegerField()),
                ('precio_lote', models.PositiveIntegerField()),
                ('fecha_ingreso', models.DateField(default=apps.cruceros.Services.fecha_general.obtener_fecha_actual)),
                ('fecha_caducidad', models.DateField(null=True)),
            ],
            options={
                'verbose_name': 'Lote de Producto',
                'verbose_name_plural': 'Lotes de Producto',
            },
        ),
        migrations.CreateModel(
            name='SeccionAlmacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('REFRIGERACION', 'Cámara de Refrigeración'), ('CONGELACION', 'Cámara de Congelación'), ('SECO', 'Almacén Seco'), ('ESTANTERIAS', 'Estanterías'), ('CUARTO_FRIO', 'Cuarto Frío'), ('SILOS', 'Silos'), ('TANQUES', 'Tanques')], max_length=20)),
                ('capacidad', models.PositiveIntegerField()),
                ('temperatura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('humedad', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('esta_activa', models.BooleanField(default=True)),
                ('almacen', models.ForeignKey(limit_choices_to={'tipo': 'almacen'}, on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='cruceros.instalacion')),
            ],
            options={
                'verbose_name': 'Sección de Almacén',
                'verbose_name_plural': 'Secciones de Almacén',
                'unique_together': {('almacen', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=100)),
                ('tipo', models.CharField(choices=[('COMIDA', 'Comida'), ('BIENES', 'Bienes')], max_length=10)),
                ('subtipo', models.CharField(blank=True, choices=[('CADUCABLE', 'Caducable'), ('NO_CADUCABLE', 'No caducable'), ('REFRIGERADO', 'Refrigerado'), ('NO_REFRIGERADO', 'No refrigerado'), ('BEBIDA', 'Bebida'), ('LICOR', 'Licor'), ('REPUESTOS', 'Repuestos'), ('LIMPIEZA', 'Materiales de limpieza'), ('MEDICOS', 'Materiales médicos'), ('ACTIVOS', 'Bienes activos')], max_length=15, null=True)),
                ('cantidad_ideal', models.PositiveIntegerField()),
                ('medida', models.CharField(choices=[('L', 'Litros'), ('M', 'Metros'), ('K', 'Kilogramos'), ('U', 'Unidades')], max_length=1)),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='almacen.seccionalmacen')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_productos', models.PositiveIntegerField()),
                ('precio_lote', models.PositiveIntegerField(help_text='Precio total esperado del lote')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('POR_REGISTRAR', 'Por registrar')], default='PENDIENTE', max_length=15)),
                ('fecha_creacion', models.DateField(default=apps.cruceros.Services.fecha_general.obtener_fecha_actual)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_compra', to='almacen.producto')),
            ],
            options={
                'verbose_name': 'Orden de Compra',
                'verbose_name_plural': 'Órdenes de Compra',
                'ordering': ['-fecha_creacion', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoAlmacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('IN', 'Ingreso'), ('OUT', 'Egreso'), ('NEW', 'Creado'), ('MERMA', 'Merma')], max_length=20)),
                ('cantidad', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha', models.DateField(default=apps.cruceros.Services.fecha_general.obtener_fecha_actual)),
                ('modulo', models.CharField(choices=[('RESTAURANTE', 'Restaurante'), ('VENTAS', 'Ventas'), ('COMPRAS', 'Compras'), ('BARES_SNACKS', 'Bares Snacks'), ('MANTENIMIENTO', 'Mantenimiento'), ('ENTRETENIMIENTO', 'Entretenimiento'), ('RECURSOS_HUMANOS', 'Recursos Humanos'), ('RESERVACIONES', 'Reservaciones'), ('ALMACEN', 'Almacén'), ('SERVICIO_MEDICO', 'Servicio Médico'), ('ADMINISTRACION', 'Administración'), ('FUERA_BARCO', 'Fuera del Barco')], max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='almacen.lote')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='almacen.producto')),
            ],
            options={
                'verbose_name': 'Movimiento de Producto',
                'verbose_name_plural': 'Movimientos de Producto',
            },
        ),
        migrations.AddField(
            model_name='lote',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='almacen.producto'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['tipo', 'subtipo'], name='indice_producto_tipo_subtipo'),
        ),
        migrations.AlterUniqueTogether(
            name='lote',
            unique_together={('producto', 'numero_lote')},
        ),
    ]
