# Generated by Django 5.2.5 on 2025-09-01 03:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoalmacen',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2025, 8, 31, 23, 11, 45, 668952)),
        ),
    ]
