# Generated by Django 5.2.6 on 2025-09-12 15:18

import apps.cruceros.Services.fecha_general
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("almacen", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SolicitudSalida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "fecha_creacion",
                    models.DateField(
                        default=apps.cruceros.Services.fecha_general.obtener_fecha_actual
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("APROBADA", "Aprobada"),
                            ("RECHAZADA", "Rechazada"),
                            ("COMPLETADA", "Completada"),
                        ],
                        default="PENDIENTE",
                        max_length=12,
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitud de Salida",
                "verbose_name_plural": "Solicitudes de Salida",
                "ordering": ["-fecha_creacion", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ProductoSolicitado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField()),
                (
                    "unidad",
                    models.CharField(
                        choices=[
                            ("L", "Litros"),
                            ("M", "Metros"),
                            ("K", "Kilogramos"),
                            ("U", "Unidades"),
                        ],
                        default="U",
                        max_length=1,
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="solicitudes",
                        to="almacen.producto",
                    ),
                ),
                (
                    "solicitud",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productos_solicitados",
                        to="almacen.solicitudsalida",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto solicitado",
                "verbose_name_plural": "Productos solicitados",
                "unique_together": {("solicitud", "producto")},
            },
        ),
    ]
