# Generated by Django 5.2.6 on 2025-09-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("almacen", "0002_solicitudsalida_productosolicitado"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitudsalida",
            name="modulo",
            field=models.CharField(
                choices=[
                    ("RESTAURANTE", "Restaurante"),
                    ("VENTAS", "Ventas"),
                    ("COMPRAS", "Compras"),
                    ("BARES_SNACKS", "Bares Snacks"),
                    ("MANTENIMIENTO", "Mantenimiento"),
                    ("ENTRETENIMIENTO", "Entretenimiento"),
                    ("RECURSOS_HUMANOS", "Recursos Humanos"),
                    ("RESERVACIONES", "Reservaciones"),
                    ("ALMACEN", "Almacén"),
                    ("SERVICIO_MEDICO", "Servicio Médico"),
                    ("ADMINISTRACION", "Administración"),
                    ("FUERA_BARCO", "Fuera del Barco"),
                ],
                default="ALMACEN",
                max_length=20,
            ),
        ),
    ]
