# Generated by Django 5.2.5 on 2025-09-01 03:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0002_alter_movimientoalmacen_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoalmacen',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2025, 8, 31, 23, 21, 34, 321054)),
        ),
    ]
