# Generated by Django 5.2.6 on 2025-09-13 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("almacen", "0003_solicitudsalida_modulo"),
        ("compras", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MensajeParaCompras",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "compra_lote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensajes_para_almacen",
                        to="compras.compralote",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensaje para Compras",
                "verbose_name_plural": "Mensajes para Compras",
            },
        ),
    ]
