# Generated by Django 5.2.4 on 2025-09-13 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0004_mensajeparacompras'),
        ('creador_embarcaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seccionalmacen',
            name='almacen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='creador_embarcaciones.embarcacion'),
        ),
    ]
