# Generated by Django 5.2.4 on 2025-09-13 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0005_alter_seccionalmacen_almacen'),
        ('creador_embarcaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seccionalmacen',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='seccionalmacen',
            name='local_tipo_almacen',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'almacen'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='creador_embarcaciones.locales'),
        ),
        migrations.RemoveField(
            model_name='seccionalmacen',
            name='almacen',
        ),
    ]
