# Generated by Django 5.2.4 on 2025-09-17 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0006_alter_seccionalmacen_unique_together_and_more'),
        ('creador_embarcaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seccionalmacen',
            name='local_tipo_almacen',
            field=models.ForeignKey(default=0, limit_choices_to={'tipo': 'almacen'}, on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='creador_embarcaciones.locales'),
            preserve_default=False,
        ),
    ]
