# Generated by Django 5.2.5 on 2025-09-03 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicaciones', '0002_remove_insumo_cantidad_inventario_bajo_stock_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='apellido',
            new_name='primer_apellido',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='apellido2',
            new_name='segundo_apellido',
        ),
    ]
