# Generated by Django 5.2.4 on 2025-09-06 09:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localRRHH', '0002_amonestacion_personal_delete_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='edad',
            field=models.PositiveIntegerField(help_text='Mayor o igual 21 años', validators=[django.core.validators.MinValueValidator(21)]),
        ),
    ]
