# Generated by Django 4.2.24 on 2025-09-13 05:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localRRHH', '0008_personal_amon_detalle_personal_amon_estado_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MainPool',
        ),
        migrations.AddField(
            model_name='personal',
            name='dia_fin',
            field=models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], default='Lunes', help_text='Día de fin de la semana laboral', max_length=10),
        ),
        migrations.AddField(
            model_name='personal',
            name='dia_inicio',
            field=models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], default='Lunes', help_text='Día de inicio de la semana laboral', max_length=10),
        ),
        migrations.AddField(
            model_name='personal',
            name='horario_entrada',
            field=models.TimeField(default=datetime.time(9, 0), help_text='Hora de entrada al trabajo'),
        ),
        migrations.AddField(
            model_name='personal',
            name='horario_salida',
            field=models.TimeField(default=datetime.time(18, 0), help_text='Hora de salida del trabajo'),
        ),
    ]
