# Generated by Django 4.2.24 on 2025-09-13 09:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localRRHH', '0009_delete_mainpool_personal_dia_fin_personal_dia_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='horario_entrada',
            field=models.TimeField(default=datetime.time(0, 0), help_text='Hora de entrada al trabajo'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='horario_salida',
            field=models.TimeField(default=datetime.time(0, 0), help_text='Hora de salida del trabajo'),
        ),
    ]
