# Generated by Django 5.2.5 on 2025-08-30 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id_actividad', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(help_text='Título de la actividad', max_length=200)),
                ('descripcion', models.TextField(help_text='Descripción completa de la actividad')),
                ('dia_crucero', models.DateField(help_text='Fecha del día del crucero')),
                ('coste', models.DecimalField(decimal_places=2, help_text='Coste de la actividad en euros', max_digits=8)),
                ('hora_inicio', models.TimeField(help_text='Hora de inicio de la actividad')),
                ('hora_fin', models.TimeField(help_text='Hora de finalización de la actividad')),
                ('maximoActividad', models.IntegerField(help_text='Número máximo de participantes')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'db_table': 'actividades_pago',
                'ordering': ['dia_crucero', 'hora_inicio'],
            },
        ),
    ]
