# Generated by Django 5.2.6 on 2025-09-13 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creador_embarcaciones', '0012_remove_habitaciones_tipo_habitaciones_posicion_and_more'),
        ('entretenimiento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='viaje',
        ),
        migrations.RemoveField(
            model_name='actividadrutinaria',
            name='viaje',
        ),
        migrations.AddField(
            model_name='actividad',
            name='embarcacion',
            field=models.ForeignKey(blank=True, help_text='Embarcación a la que pertenece esta actividad', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='creador_embarcaciones.embarcacion'),
        ),
        migrations.AddField(
            model_name='actividadrutinaria',
            name='embarcacion',
            field=models.ForeignKey(blank=True, help_text='Embarcación a la que pertenece esta actividad rutinaria', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actividades_rutinarias', to='creador_embarcaciones.embarcacion'),
        ),
    ]
