# Generated by Django 5.2.5 on 2025-08-30 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entretenimiento', '0002_actividadrutinaria_alter_actividad_dia_crucero'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividadrutinaria',
            name='ubicacion',
            field=models.CharField(default='Sin asignar', help_text='Ubicación donde se realiza la actividad', max_length=200),
            preserve_default=False,
        ),
    ]
