# Generated by Django 5.2.5 on 2025-08-31 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entretenimiento', '0003_actividadrutinaria_ubicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroActividadPago',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre del cliente', max_length=100)),
                ('apellido', models.CharField(help_text='Apellido del cliente', max_length=100)),
                ('n_habitacion', models.CharField(help_text='Número de habitación del cliente', max_length=20)),
                ('n_personas', models.IntegerField(help_text='Número de personas incluidas en el registro')),
                ('monto_total', models.DecimalField(decimal_places=2, help_text='Monto total del pago', max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('pagado', 'Pagado'), ('cancelado', 'Cancelado')], default='pendiente', help_text='Estado actual del registro', max_length=20)),
                ('id_factura', models.CharField(help_text='Identificador único de la factura', max_length=50, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro')),
            ],
            options={
                'verbose_name': 'Registro de Actividad de Pago',
                'verbose_name_plural': 'Registros de Actividades de Pago',
                'db_table': 'registro_actividad_pago',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
