# Generated by Django 5.2.5 on 2025-08-31 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entretenimiento', '0004_registroactividadpago'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroActividadRut',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre del cliente', max_length=100)),
                ('apellido', models.CharField(help_text='Apellido del cliente', max_length=100)),
                ('n_habitacion', models.CharField(help_text='Número de habitación del cliente', max_length=20)),
                ('n_personas', models.IntegerField(help_text='Número de personas incluidas en el registro')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro')),
            ],
            options={
                'verbose_name': 'Registro de Actividad Rutinaria',
                'verbose_name_plural': 'Registros de Actividades Rutinarias',
                'db_table': 'registro_actividad_rut',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
