# Generated by Django 5.2.4 on 2025-09-01 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entretenimiento', '0005_registroactividadrut'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='img_src',
            field=models.CharField(blank=True, help_text='URL o ruta de la imagen de la actividad', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='actividadrutinaria',
            name='img_src',
            field=models.CharField(blank=True, help_text='URL o ruta de la imagen de la actividad', max_length=500, null=True),
        ),
    ]
