# Generated by Django 5.2.5 on 2025-08-30 22:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entretenimiento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadRutinaria',
            fields=[
                ('id_actividad', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(help_text='Título de la actividad rutinaria', max_length=200)),
                ('descripcion', models.TextField(help_text='Descripción completa de la actividad rutinaria')),
                ('dia_crucero', models.IntegerField(choices=[(1, 'Día 1'), (2, 'Día 2'), (3, 'Día 3'), (4, 'Día 4'), (5, 'Día 5'), (6, 'Día 6'), (7, 'Día 7'), (8, 'Día 8')], help_text='Día del crucero (1-8)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('hora_inicio', models.TimeField(help_text='Hora de inicio de la actividad')),
                ('hora_fin', models.TimeField(help_text='Hora de finalización de la actividad')),
                ('maximo_actividad', models.IntegerField(help_text='Número máximo de participantes')),
            ],
            options={
                'verbose_name': 'Actividad Rutinaria',
                'verbose_name_plural': 'Actividades Rutinarias',
                'db_table': 'actividad_rutinaria',
                'ordering': ['dia_crucero', 'hora_inicio'],
            },
        ),
        migrations.AlterField(
            model_name='actividad',
            name='dia_crucero',
            field=models.IntegerField(choices=[(1, 'Día 1'), (2, 'Día 2'), (3, 'Día 3'), (4, 'Día 4'), (5, 'Día 5'), (6, 'Día 6'), (7, 'Día 7'), (8, 'Día 8')], help_text='Día del crucero (1-8)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)]),
        ),
    ]
