# Generated by Django 4.2.7 on 2025-09-01 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mantenimiento', '0003_personal_tareamantenimiento_tipo_crucero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareamantenimiento',
            name='estado',
            field=models.CharField(choices=[('creada', 'Creada'), ('planificada', 'Planificada'), ('asignada', 'Asignada'), ('en_progreso', 'En Progreso'), ('esperando_materiales', 'Esperando Materiales'), ('esperando_personal', 'Esperando Personal'), ('pausada', 'Pausada'), ('revision', 'En Revisión'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('rechazada', 'Rechazada')], default='creada', max_length=25),
        ),
        migrations.AlterField(
            model_name='tareamantenimiento',
            name='prioridad',
            field=models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica'), ('emergencia', 'Emergencia Crítica')], default='media', max_length=20),
        ),
        migrations.AlterField(
            model_name='tareamantenimiento',
            name='tipo',
            field=models.CharField(choices=[('preventivo', 'Mantenimiento Preventivo'), ('correctivo', 'Mantenimiento Correctivo'), ('emergencia', 'Emergencia'), ('inspeccion', 'Inspección'), ('limpieza', 'Limpieza'), ('reparacion', 'Reparación')], max_length=20),
        ),
        migrations.CreateModel(
            name='CambioEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(max_length=25)),
                ('estado_nuevo', models.CharField(max_length=25)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios_estado', to='mantenimiento.tareamantenimiento')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_cambio'],
            },
        ),
    ]
