# Generated by Django 4.2.7 on 2025-09-01 16:39

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0004_alter_tareamantenimiento_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Piscina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('volumen_m3', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))])),
                ('en_servicio', models.BooleanField(default=True)),
                ('fecha_ultima_limpieza', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('tipo_crucero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mantenimiento.tipocrucero')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.ubicacion')),
            ],
            options={
                'verbose_name': 'Piscina',
                'verbose_name_plural': 'Piscinas',
            },
        ),
        migrations.CreateModel(
            name='MedicionPiscina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('ph', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('14.0'))])),
                ('cloro_mg_l', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('10.0'))])),
                ('temperatura_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('turbidez_ntu', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('presion_filtro_bar', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('estado_filtro', models.CharField(choices=[('ok', 'OK'), ('retrolavado', 'Requiere Retrolavado'), ('mantenimiento', 'Mantenimiento Requerido')], default='ok', max_length=20)),
                ('retrolavado_realizado', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True)),
                ('piscina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediciones', to='mantenimiento.piscina')),
            ],
            options={
                'verbose_name': 'Medición de Piscina',
                'verbose_name_plural': 'Mediciones de Piscina',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
