# Generated by Django 4.2.7 on 2025-09-01 17:51

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mantenimiento', '0005_piscina_medicionpiscina'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tipo_tarea', models.CharField(choices=[('preventivo', 'Mantenimiento Preventivo'), ('correctivo', 'Mantenimiento Correctivo'), ('emergencia', 'Emergencia'), ('inspeccion', 'Inspección'), ('limpieza', 'Limpieza'), ('reparacion', 'Reparación')], max_length=20)),
                ('tiempo_estimado_horas', models.DecimalField(decimal_places=2, default=Decimal('1.0'), max_digits=5)),
                ('prioridad_default', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica'), ('emergencia', 'Emergencia Crítica')], default='media', max_length=20)),
                ('instrucciones', models.TextField(help_text='Instrucciones paso a paso')),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plantilla de Tarea',
                'verbose_name_plural': 'Plantillas de Tareas',
            },
        ),
        migrations.AddField(
            model_name='reporteincidente',
            name='tipo_crucero',
            field=models.ForeignKey(blank=True, help_text='Tipo de crucero donde ocurrió el incidente', null=True, on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.tipocrucero'),
        ),
        migrations.CreateModel(
            name='ProductoPlantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_estimada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('obligatorio', models.BooleanField(default=True)),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.plantillatarea')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.producto')),
            ],
        ),
        migrations.AddField(
            model_name='plantillatarea',
            name='productos_necesarios',
            field=models.ManyToManyField(blank=True, through='mantenimiento.ProductoPlantilla', to='mantenimiento.producto'),
        ),
        migrations.AddField(
            model_name='plantillatarea',
            name='tipo_equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.tipoequipo'),
        ),
        migrations.AddField(
            model_name='plantillatarea',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.ubicacion'),
        ),
        migrations.CreateModel(
            name='MantenimientoRecurrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('frecuencia', models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('quincenal', 'Quincenal'), ('mensual', 'Mensual'), ('bimestral', 'Bimestral'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], max_length=20)),
                ('dias_adelanto', models.IntegerField(default=0, help_text='Días de anticipación para crear la tarea')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('ultima_generacion', models.DateTimeField(blank=True, null=True)),
                ('plantilla_tarea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.plantillatarea')),
                ('tipo_crucero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.tipocrucero')),
                ('tipo_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.tipoequipo')),
            ],
            options={
                'verbose_name': 'Mantenimiento Recurrente',
                'verbose_name_plural': 'Mantenimientos Recurrentes',
            },
        ),
        migrations.CreateModel(
            name='FiltroGuardado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('filtros', models.JSONField(default=dict)),
                ('publico', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Filtro Guardado',
                'verbose_name_plural': 'Filtros Guardados',
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=300)),
                ('completado', models.BooleanField(default=False)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('orden', models.IntegerField(default=1)),
                ('obligatorio', models.BooleanField(default=True)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='mantenimiento.tareamantenimiento')),
                ('usuario_completado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AdjuntoTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='adjuntos_tareas/%Y/%m/')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('imagen', 'Imagen'), ('pdf', 'PDF'), ('documento', 'Documento'), ('otro', 'Otro')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='mantenimiento.tareamantenimiento')),
            ],
            options={
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
