# Generated by Django 5.2.4 on 2025-09-13 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_dias', models.IntegerField(verbose_name='Número de días')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título de la ruta')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción de la ruta')),
                ('max_dias', models.IntegerField(verbose_name='Máximo de días')),
                ('crucero', models.CharField(max_length=100, verbose_name='Crucero')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Ruta',
                'verbose_name_plural': 'Rutas',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Embarcacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la embarcación')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo de embarcación')),
                ('identificador', models.CharField(max_length=20, unique=True, verbose_name='Identificador único')),
                ('fecha_botadura', models.DateField(verbose_name='Fecha de botadura')),
                ('fecha_adquisicion', models.DateField(verbose_name='Fecha de adquisición')),
                ('capacidad_pasajeros', models.IntegerField(verbose_name='Capacidad de pasajeros')),
                ('capacidad_tripulacion', models.IntegerField(verbose_name='Capacidad de tripulación')),
                ('tonelaje', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tonelaje (toneladas)')),
                ('eslora', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Eslora (metros)')),
                ('manga', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Manga (metros)')),
                ('altura', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Altura (metros)')),
                ('numero_cubiertas', models.IntegerField(verbose_name='Número de cubiertas')),
                ('area_utilizable', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Área utilizable (m²)')),
                ('maximo_habitacion_pasajeros', models.IntegerField(verbose_name='Máximo habitaciones para pasajeros')),
                ('maximo_habitacion_tripulantes', models.IntegerField(verbose_name='Máximo habitaciones para tripulantes')),
                ('bandera', models.CharField(max_length=50, verbose_name='Bandera')),
                ('puerto_base', models.CharField(max_length=100, verbose_name='Puerto base')),
                ('estado_operativo', models.CharField(choices=[('operativo', 'Operativo'), ('mantenimiento', 'En mantenimiento'), ('reparacion', 'En reparación'), ('inactivo', 'Inactivo')], default='operativo', max_length=20, verbose_name='Estado operativo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('modelo_motor', models.CharField(max_length=100, verbose_name='Modelo del motor')),
                ('velocidad_maxima', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Velocidad máxima (nudos)')),
                ('ultimo_mantenimiento', models.DateField(verbose_name='Último mantenimiento')),
                ('proximo_mantenimiento', models.DateField(verbose_name='Próximo mantenimiento')),
                ('tipo_combustible', models.CharField(choices=[('diesel', 'Diésel'), ('gasolina', 'Gasolina'), ('gas_natural', 'Gas Natural'), ('electrico', 'Eléctrico'), ('hibrido', 'Híbrido')], max_length=20, verbose_name='Tipo de combustible')),
                ('consumo_combustible', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Consumo de combustible (L/hora)')),
                ('capacidad_combustible', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Capacidad de combustible (litros)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('ruta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='creador_embarcaciones.ruta', verbose_name='Ruta asignada')),
            ],
            options={
                'verbose_name': 'Embarcación',
                'verbose_name_plural': 'Embarcaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
