# Generated by Django 5.2.4 on 2025-09-13 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creador_embarcaciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruta',
            name='max_dias',
        ),
    ]
