# Generated by Django 5.2.4 on 2025-09-13 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creador_embarcaciones', '0002_remove_ruta_max_dias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruta',
            name='crucero',
        ),
    ]
