# Generated by Django 5.2.4 on 2025-09-13 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creador_embarcaciones', '0003_remove_ruta_crucero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_dia', models.IntegerField(verbose_name='Número del día')),
                ('ubicacion', models.CharField(help_text='Lugar donde estará la embarcación este día', max_length=200, verbose_name='Ubicación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='creador_embarcaciones.ruta', verbose_name='Ruta')),
            ],
            options={
                'verbose_name': 'Día',
                'verbose_name_plural': 'Días',
                'ordering': ['ruta', 'numero_dia'],
                'unique_together': {('ruta', 'numero_dia')},
            },
        ),
    ]
