# Generated by Django 5.2.4 on 2025-09-13 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creador_embarcaciones', '0004_dia'),
    ]

    operations = [
        migrations.AddField(
            model_name='dia',
            name='actividades',
            field=models.TextField(blank=True, help_text='Lista de actividades específicas del día', verbose_name='Actividades programadas'),
        ),
        migrations.AddField(
            model_name='dia',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Actividades, atracciones y detalles del día', verbose_name='Descripción del día'),
        ),
        migrations.AddField(
            model_name='dia',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de configuración'), ('configurado', 'Configurado'), ('confirmado', 'Confirmado')], default='pendiente', max_length=20, verbose_name='Estado de configuración'),
        ),
        migrations.AddField(
            model_name='dia',
            name='hora_llegada',
            field=models.TimeField(blank=True, help_text='Hora estimada de llegada al destino', null=True, verbose_name='Hora de llegada'),
        ),
        migrations.AddField(
            model_name='dia',
            name='hora_salida',
            field=models.TimeField(blank=True, help_text='Hora estimada de salida del destino', null=True, verbose_name='Hora de salida'),
        ),
        migrations.AddField(
            model_name='dia',
            name='notas_especiales',
            field=models.TextField(blank=True, help_text='Información adicional importante para este día', verbose_name='Notas especiales'),
        ),
        migrations.AddField(
            model_name='dia',
            name='titulo_dia',
            field=models.CharField(default='Día pendiente de configuración', help_text='Título descriptivo para este día', max_length=100, verbose_name='Título del día'),
        ),
        migrations.AlterField(
            model_name='dia',
            name='ubicacion',
            field=models.CharField(default='Ubicación pendiente', help_text='Lugar donde estará la embarcación este día', max_length=200, verbose_name='Ubicación'),
        ),
    ]
