# Generated by Django 5.2.4 on 2025-09-13 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creador_embarcaciones', '0005_dia_actividades_dia_descripcion_dia_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dia',
            name='actividades',
        ),
        migrations.RemoveField(
            model_name='dia',
            name='estado',
        ),
        migrations.AlterField(
            model_name='dia',
            name='hora_llegada',
            field=models.TimeField(default='08:00:00', help_text='Hora estimada de llegada al destino', verbose_name='Hora de llegada'),
        ),
        migrations.AlterField(
            model_name='dia',
            name='hora_salida',
            field=models.TimeField(default='17:00:00', help_text='Hora estimada de salida del destino', verbose_name='Hora de salida'),
        ),
    ]
