# Generated by Django 5.2.4 on 2025-09-13 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creador_embarcaciones', '0006_remove_dia_actividades_remove_dia_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEmbarcacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre del tipo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción del tipo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Tipo de Embarcación',
                'verbose_name_plural': 'Tipos de Embarcación',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='embarcacion',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='creador_embarcaciones.tipoembarcacion', verbose_name='Tipo de embarcación'),
        ),
    ]
