# Generated by Django 5.2.4 on 2025-09-13 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creador_embarcaciones', '0007_tipoembarcacion_alter_embarcacion_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embarcacion',
            name='identificador',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Identificador único'),
        ),
    ]
