# Generated by Django 5.2.6 on 2025-09-13 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creador_embarcaciones', '0008_alter_embarcacion_identificador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embarcacion',
            name='estado_operativo',
            field=models.CharField(choices=[('en_espera', 'En espera'), ('operativo', 'Operativo'), ('mantenimiento', 'En mantenimiento'), ('reparacion', 'En reparación'), ('inactivo', 'Inactivo')], default='en_espera', max_length=20, verbose_name='Estado operativo'),
        ),
        migrations.CreateModel(
            name='Cubierta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la cubierta')),
                ('numero', models.IntegerField(verbose_name='Número de cubierta')),
                ('area_disponible', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Área disponible (m²)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('embarcacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cubiertas', to='creador_embarcaciones.embarcacion', verbose_name='Embarcación')),
            ],
            options={
                'verbose_name': 'Cubierta',
                'verbose_name_plural': 'Cubiertas',
                'ordering': ['embarcacion', 'numero'],
                'unique_together': {('embarcacion', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Habitaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='Número de habitación')),
                ('ID_local', models.CharField(max_length=20, unique=True, verbose_name='ID único de la habitación')),
                ('tipo', models.CharField(choices=[('babor', 'Habitación en babor'), ('estribor', 'Habitación en estribor')], max_length=20, verbose_name='Tipo de habitación')),
                ('area_metros_cuadrados', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Área (m²)')),
                ('n_cubierta', models.IntegerField(verbose_name='Número de cubierta')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('ocupada', 'Ocupada'), ('mantenimiento', 'En mantenimiento'), ('cerrada', 'Cerrada'), ('construccion', 'En construcción')], default='disponible', max_length=20, verbose_name='Estado')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio por noche (€)')),
                ('id_persona', models.CharField(blank=True, max_length=50, verbose_name='ID de persona asignada')),
                ('ultimo_mantenimiento', models.DateField(verbose_name='Último mantenimiento')),
                ('proximo_mantenimiento', models.DateField(verbose_name='Próximo mantenimiento')),
                ('ubicacion', models.CharField(max_length=50, unique=True, verbose_name='Ubicación única')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('cubierta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habitaciones', to='creador_embarcaciones.cubierta', verbose_name='Cubierta')),
            ],
            options={
                'verbose_name': 'Habitación',
                'verbose_name_plural': 'Habitaciones',
                'ordering': ['cubierta', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='Locales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('restaurante', 'Restaurante'), ('bar', 'Bar'), ('piscina', 'Piscina'), ('entretenimientos', 'Entretenimientos'), ('oficinas', 'Oficinas'), ('almacen', 'Almacén'), ('servicio_medico', 'Servicio Médico'), ('lobby', 'Lobby')], max_length=20, verbose_name='Tipo de local')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del local')),
                ('ID_local', models.CharField(max_length=20, unique=True, verbose_name='ID único del local')),
                ('estado', models.CharField(choices=[('operativo', 'Operativo'), ('mantenimiento', 'En mantenimiento'), ('cerrado', 'Cerrado'), ('construccion', 'En construcción')], default='operativo', max_length=20, verbose_name='Estado')),
                ('area_metros_cuadrados', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Área (m²)')),
                ('n_cubierta', models.IntegerField(verbose_name='Número de cubierta')),
                ('ultimo_mantenimiento', models.DateField(verbose_name='Último mantenimiento')),
                ('proximo_mantenimiento', models.DateField(verbose_name='Próximo mantenimiento')),
                ('ubicacion', models.CharField(max_length=50, unique=True, verbose_name='Ubicación única')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('cubierta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locales', to='creador_embarcaciones.cubierta', verbose_name='Cubierta')),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locales',
                'ordering': ['cubierta', 'tipo', 'nombre'],
            },
        ),
    ]
