# Generated by Django 5.2.6 on 2025-09-13 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creador_embarcaciones', '0009_alter_embarcacion_estado_operativo_cubierta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del tipo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('tipo', models.CharField(choices=[('babor', 'Habitación en babor'), ('estribor', 'Habitación en estribor')], max_length=20, verbose_name='Tipo de habitación')),
                ('area_metros_cuadrados', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Área estándar (m²)')),
                ('precio_base', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Precio base (€)')),
                ('estado_default', models.CharField(choices=[('disponible', 'Disponible'), ('ocupada', 'Ocupada'), ('mantenimiento', 'En mantenimiento'), ('cerrada', 'Cerrada'), ('construccion', 'En construcción')], default='disponible', max_length=20, verbose_name='Estado por defecto')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Tipo de Habitación',
                'verbose_name_plural': 'Tipos de Habitación',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del tipo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('tipo', models.CharField(choices=[('restaurante', 'Restaurante'), ('bar', 'Bar'), ('piscina', 'Piscina'), ('entretenimientos', 'Entretenimientos'), ('oficinas', 'Oficinas'), ('almacen', 'Almacén'), ('servicio_medico', 'Servicio Médico'), ('lobby', 'Lobby')], max_length=20, verbose_name='Tipo de local')),
                ('area_metros_cuadrados', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Área estándar (m²)')),
                ('estado_default', models.CharField(choices=[('operativo', 'Operativo'), ('mantenimiento', 'En mantenimiento'), ('cerrado', 'Cerrado'), ('construccion', 'En construcción')], default='operativo', max_length=20, verbose_name='Estado por defecto')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Tipo de Local',
                'verbose_name_plural': 'Tipos de Local',
                'ordering': ['nombre'],
            },
        ),
    ]
