# Generated by Django 5.2.6 on 2025-09-13 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creador_embarcaciones', '0010_tipohabitacion_tipolocal'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipohabitacion',
            name='capacidad_personas',
            field=models.IntegerField(default=2, verbose_name='Capacidad de personas'),
        ),
        migrations.AddField(
            model_name='tipohabitacion',
            name='numero_camas',
            field=models.IntegerField(default=1, verbose_name='Número de camas'),
        ),
        migrations.AddField(
            model_name='tipohabitacion',
            name='proximo_mantenimiento_dias',
            field=models.IntegerField(default=180, verbose_name='Días para próximo mantenimiento'),
        ),
        migrations.AddField(
            model_name='tipohabitacion',
            name='tiene_balcon',
            field=models.BooleanField(default=False, verbose_name='Tiene balcón'),
        ),
        migrations.AddField(
            model_name='tipohabitacion',
            name='tiene_bano_privado',
            field=models.BooleanField(default=True, verbose_name='Tiene baño privado'),
        ),
        migrations.AddField(
            model_name='tipohabitacion',
            name='tiene_vista_mar',
            field=models.BooleanField(default=False, verbose_name='Tiene vista al mar'),
        ),
        migrations.AddField(
            model_name='tipohabitacion',
            name='ultimo_mantenimiento_dias',
            field=models.IntegerField(default=30, verbose_name='Días para último mantenimiento'),
        ),
        migrations.AddField(
            model_name='tipolocal',
            name='capacidad_personas',
            field=models.IntegerField(default=50, verbose_name='Capacidad de personas'),
        ),
        migrations.AddField(
            model_name='tipolocal',
            name='proximo_mantenimiento_dias',
            field=models.IntegerField(default=90, verbose_name='Días para próximo mantenimiento'),
        ),
        migrations.AddField(
            model_name='tipolocal',
            name='tiene_iluminacion_especial',
            field=models.BooleanField(default=False, verbose_name='Tiene iluminación especial'),
        ),
        migrations.AddField(
            model_name='tipolocal',
            name='tiene_ventilacion',
            field=models.BooleanField(default=True, verbose_name='Tiene ventilación'),
        ),
        migrations.AddField(
            model_name='tipolocal',
            name='ultimo_mantenimiento_dias',
            field=models.IntegerField(default=30, verbose_name='Días para último mantenimiento'),
        ),
    ]
