# Generated by Django 5.2.4 on 2025-09-13 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creador_embarcaciones', '0011_tipohabitacion_capacidad_personas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitaciones',
            name='tipo',
        ),
        migrations.AddField(
            model_name='habitaciones',
            name='posicion',
            field=models.CharField(choices=[('babor', 'Babor'), ('estribor', 'Estribor')], default='babor', max_length=20, verbose_name='Posición'),
        ),
        migrations.AddField(
            model_name='habitaciones',
            name='tipo_habitacion_estandar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='habitaciones', to='creador_embarcaciones.tipohabitacion', verbose_name='Tipo de habitación estándar'),
        ),
        migrations.AlterField(
            model_name='tipohabitacion',
            name='tipo',
            field=models.CharField(choices=[('babor', 'Babor'), ('estribor', 'Estribor')], max_length=20, verbose_name='Tipo de habitación'),
        ),
    ]
