# Generated by Django 5.2.4 on 2025-09-13 07:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cruceros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Paises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CompraLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_nombre', models.CharField(max_length=100)),
                ('empresa_contacto', models.CharField(max_length=100)),
                ('empresa_ubicacion', models.CharField(max_length=100)),
                ('puerto_entrega', models.CharField(max_length=100)),
                ('notas_compra', models.TextField(blank=True)),
                ('presupuesto_lote', models.DecimalField(decimal_places=2, max_digits=15)),
                ('estado', models.CharField(choices=[('registrada', 'Registrada'), ('espera_revision', 'En espera por revisión'), ('exitosa', 'Exitosa'), ('defectuosa', 'Defectuosa'), ('cancelada', 'Cancelada')], default='registrada', max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('crucero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras_por_lote', to='cruceros.crucero')),
            ],
        ),
        migrations.CreateModel(
            name='CompraLoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_id', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('medida', models.CharField(max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compra_lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='compras.compralote')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('service_or_product', models.CharField(max_length=100)),
                ('categorie', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('sucursal', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('ALIMENTOS_FRESCOS', 'Alimentos Frescos'), ('ALIMENTOS_SECOS', 'Alimentos Secos'), ('BEBIDAS', 'Bebidas'), ('INSUMOS_COCINA', 'Insumos de Cocina'), ('LIMPIEZA', 'Limpieza'), ('SUMINISTROS_MEDICOS', 'Suministros Médicos'), ('MANTENIMIENTO', 'Materiales de Mantenimiento'), ('REPUESTOS_TECNICOS', 'Repuestos Técnicos'), ('EQUIPOS', 'Equipos'), ('TEXTILES', 'Textiles'), ('OFICINA', 'Oficina'), ('ENTRETENIMIENTO', 'Entretenimiento'), ('SPA_GYM', 'SPA / GYM'), ('SEGURIDAD', 'Seguridad'), ('MERCHANDISING', 'Merchandising'), ('TECNOLOGIA', 'Tecnología')], max_length=20)),
                ('subtipo', models.CharField(blank=True, choices=[('FRUTA', 'Fruta'), ('VERDURA', 'Verdura'), ('CARNE', 'Carne'), ('PESCADO', 'Pescado'), ('MARISCO', 'Marisco'), ('LACTEOS', 'Lácteos'), ('PANIFICADOS', 'Panificados'), ('CHARCUTERIA', 'Charcutería'), ('CEREAL', 'Cereal'), ('PASTA', 'Pasta'), ('LEGUMINOSAS', 'Leguminosas'), ('ENLATADOS', 'Enlatados'), ('SNACKS', 'Snacks'), ('CONDIMENTOS', 'Condimentos'), ('AZUCAR_SAL', 'Azúcar / Sal'), ('AGUA', 'Agua'), ('REFRESCO', 'Refresco'), ('JUGO', 'Jugo'), ('ENERGETICA', 'Energética'), ('CAFE_TEA', 'Café / Té'), ('CERVEZA', 'Cerveza'), ('VINO', 'Vino'), ('DESTILADO', 'Destilado'), ('COCTEL_PREMEZCLA', 'Cóctel Premezclado'), ('DESCARTABLES', 'Descartables'), ('ENVASES', 'Envases'), ('UTENSILIOS', 'Utensilios'), ('GAS_COCINA', 'Gas Cocina'), ('HIELO', 'Hielo'), ('DETERGENTES', 'Detergentes'), ('DESINFECTANTES', 'Desinfectantes'), ('UTENSILIOS_LIMPIEZA', 'Utensilios Limpieza'), ('PAPEL_SANITARIO', 'Papel Sanitario'), ('AMBIENTADORES', 'Ambientadores'), ('MEDICAMENTO', 'Medicamento'), ('CURACION', 'Curación'), ('EQUIPO_DIAGNOSTICO', 'Equipo Diagnóstico'), ('EPP', 'Equipo Protección Personal'), ('INSTRUMENTAL', 'Instrumental'), ('SOLUCION_IV', 'Solución IV'), ('PINTURA', 'Pintura'), ('LUBRICANTE', 'Lubricante'), ('SELLADOR', 'Sellador'), ('ADHESIVO', 'Adhesivo'), ('ABRASIVO', 'Abrasivo'), ('FILTRO', 'Filtro'), ('ACEITE', 'Aceite'), ('MOTOR', 'Motor'), ('ELECTRICO', 'Eléctrico'), ('HVAC', 'HVAC'), ('NAVEGACION', 'Navegación'), ('ILUMINACION', 'Iluminación'), ('BOMBAS', 'Bombas'), ('VALVULAS', 'Válvulas'), ('ELECTRODOMESTICO', 'Electrodoméstico'), ('AUDIO_VIDEO', 'Audio / Video'), ('INFORMATICO', 'Informático'), ('GIMNASIO', 'Gimnasio'), ('COCINA_INDUSTRIAL', 'Cocina Industrial'), ('ROPA_CAMA', 'Ropa de Cama'), ('TOALLA', 'Toalla'), ('UNIFORME', 'Uniforme'), ('CORTINA', 'Cortina'), ('TAPICERIA', 'Tapicería'), ('PAPELERIA', 'Papelería'), ('IMPRESION', 'Impresión'), ('ESCRITORIO', 'Escritorio'), ('CONSUMIBLE_IT', 'Consumible IT'), ('JUEGO_MESA', 'Juego de Mesa'), ('JUEGO_VIDEO', 'Videojuego'), ('LIBRO_REVISTA', 'Libro / Revista'), ('EVENTO', 'Evento'), ('SONIDO_LUZ', 'Sonido / Luz'), ('COSMETICO', 'Cosmético'), ('ACEITE_MASAJE', 'Aceite de Masaje'), ('SUPLEMENTO', 'Suplemento'), ('ACC_FITNESS', 'Accesorio Fitness'), ('CHALECO_SALVAVIDAS', 'Chaleco Salvavidas'), ('EXTINTOR', 'Extintor'), ('SENALIZACION', 'Señalización'), ('ARNES', 'Arnés'), ('BOTIQUIN', 'Botiquín'), ('DETECTOR', 'Detector'), ('RECUERDO', 'Recuerdo'), ('PRENDA_LOGO', 'Prenda con Logo'), ('ACCESORIO_LOGO', 'Accesorio con Logo'), ('BEBIDA_PREMIUM', 'Bebida Premium'), ('DULCE_GOURMET', 'Dulce Gourmet'), ('ROUTER', 'Router'), ('SWITCH', 'Switch'), ('CABLEADO', 'Cableado'), ('CAMARA_SEGURIDAD', 'Cámara de Seguridad'), ('SENSOR', 'Sensor'), ('DISPOSITIVO_PORTATIL', 'Dispositivo Portátil')], max_length=20, null=True)),
                ('countries', models.ManyToManyField(to='compras.paises')),
            ],
        ),
        migrations.AddField(
            model_name='compralote',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compras.proveedores'),
        ),
        migrations.CreateModel(
            name='SolicitudSubtipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('subtipo', models.CharField(max_length=50)),
                ('procesada', models.BooleanField(default=False)),
                ('crucero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_de_compra', to='cruceros.crucero')),
            ],
        ),
        migrations.AddField(
            model_name='compralote',
            name='solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes', to='compras.solicitudsubtipo'),
        ),
        migrations.CreateModel(
            name='SolicitudSubtipoItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('producto_id', models.IntegerField()),
                ('nombre', models.CharField(max_length=200)),
                ('cantidad_a_comprar', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10000)])),
                ('medida', models.CharField(max_length=20)),
                ('tipo', models.CharField(max_length=50)),
                ('subtipo', models.CharField(max_length=50)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='compras.solicitudsubtipo')),
            ],
        ),
        migrations.CreateModel(
            name='ProveedorMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_unidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.material')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.proveedores')),
            ],
            options={
                'unique_together': {('proveedor', 'material')},
            },
        ),
    ]
