# Generated by Django 5.2.4 on 2025-09-13 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        # Renombrar columna crucero_id a embarcacion_id en CompraLote
        migrations.RenameField(
            model_name='compraLote',
            old_name='crucero',
            new_name='embarcacion',
        ),
        # Renombrar columna crucero_id a embarcacion_id en SolicitudSubtipo
        migrations.RenameField(
            model_name='solicitudSubtipo',
            old_name='crucero',
            new_name='embarcacion',
        ),
    ]
