# Generated by Django 5.2.4 on 2025-09-17 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_auto_20250913_0523'),
        ('creador_embarcaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compralote',
            name='embarcacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras_por_lote', to='creador_embarcaciones.embarcacion'),
        ),
        migrations.AlterField(
            model_name='solicitudsubtipo',
            name='embarcacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_de_compra', to='creador_embarcaciones.embarcacion'),
        ),
    ]
