# Generated by Django 5.2.5 on 2025-09-06 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cruceros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entretenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crucero', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('dia', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('reservada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EventoPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crucero', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('materiales', models.TextField(blank=True, null=True)),
                ('dia', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, default=700.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crucero', models.CharField(max_length=20)),
                ('numero', models.CharField(max_length=10)),
                ('capacidad', models.IntegerField(default=4)),
                ('reservada', models.BooleanField(default=False)),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crucero', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crucero', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('dia_actual', models.PositiveIntegerField(default=0)),
                ('total_dias', models.PositiveIntegerField(default=8)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('entretenimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservaciones.entretenimiento')),
                ('evento_personalizado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservaciones.eventopersonalizado')),
                ('habitacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cruceros.habitacion')),
                ('mesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservaciones.mesa')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='mesa',
            name='restaurante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesas', to='reservaciones.restaurante'),
        ),
    ]
