# Generated by Django 5.2.5 on 2025-09-06 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entretenimiento', '0001_initial'),
        ('reservaciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='entretenimiento',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='habitacion',
        ),
        migrations.AddField(
            model_name='reserva',
            name='actividad_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas_pago', to='entretenimiento.actividad'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='actividad_rutinaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas_rutinarias', to='entretenimiento.actividadrutinaria'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='apellido_cliente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='codigo_ubicacion_habitacion',
            field=models.CharField(blank=True, help_text='Código UUAIII de la habitación reservada', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='costo_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_nacimiento_cliente',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='nombre_cliente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='numero_personas',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
