# Generated by Django 5.2.5 on 2025-09-03 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entretenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('crucero', models.CharField(choices=[('vision', 'Vision of the Seas'), ('voyager', 'Voyager of the Seas'), ('oasis', 'Oasis of the Seas')], max_length=20)),
                ('dia', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('reservada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crucero', models.CharField(choices=[('vision', 'Vision of the Seas (Pequeño)'), ('voyager', 'Voyager of the Seas (Mediano)'), ('oasis', 'Oasis of the Seas (Grande)')], max_length=20)),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('piso', models.IntegerField(default=1)),
                ('lado', models.CharField(choices=[('babor', 'Babor'), ('estribor', 'Estribor')], max_length=10)),
                ('vista_mar', models.BooleanField(default=False)),
                ('reservada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TipoHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('basico', 'Camarote Básico'), ('premium', 'Camarote Premium')], default='basico', max_length=20)),
                ('subtipo', models.CharField(choices=[('sencillo', 'Sencillo (2 personas)'), ('doble', 'Doble (4 personas)')], default='sencillo', max_length=20)),
                ('capacidad', models.IntegerField(default=2)),
                ('precio_base', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dia_actual', models.PositiveIntegerField(default=1)),
                ('total_dias', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('entretenimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='App.entretenimiento')),
                ('habitacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='App.habitacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='habitacion',
            name='tipo_habitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.tipohabitacion'),
        ),
        migrations.CreateModel(
            name='Itinerario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.PositiveIntegerField()),
                ('destino', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerario', to='App.viaje')),
            ],
            options={
                'ordering': ['dia'],
                'unique_together': {('viaje', 'dia')},
            },
        ),
    ]
