# Generated by Django 5.2.5 on 2025-09-05 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventopersonalizado',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=700.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='mesa',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
