# Generated by Django 5.2.6 on 2025-09-06 10:39

import apps.recursos_humanos.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=10, validators=[apps.recursos_humanos.models.validate_name])),
                ('apellido', models.CharField(max_length=10, validators=[apps.recursos_humanos.models.validate_name])),
                ('salario', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999999)])),
                ('edad', models.PositiveIntegerField(help_text='Mayor o igual 21 años', validators=[django.core.validators.MinValueValidator(21)])),
                ('anios_experiencia', models.PositiveIntegerField()),
                ('categoria', models.CharField(choices=[('Culinario', 'Culinario'), ('Medico', 'Medico'), ('Administrativo', 'Administrativo'), ('Mantenimiento', 'Mantenimiento'), ('Entretenimiento', 'Entretenimiento'), ('Personal Extra', 'Personal Extra')], max_length=20)),
                ('puesto', models.CharField(max_length=30)),
                ('pStatus', models.IntegerField(choices=[(1, 'Activo'), (2, 'Inactivo'), (3, 'De baja')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Amonestacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=False)),
                ('detalle', models.CharField(blank=True, max_length=50, null=True)),
                ('personal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='amonestacion', to='recursos_humanos.personal')),
            ],
        ),
    ]
