# Generated by Django 5.2.6 on 2025-09-06 02:45

import django.core.validators
import django.db.models.deletion
import localRRHH.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localRRHH', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amonestacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=False)),
                ('detalle', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=10, validators=[localRRHH.models.validate_name])),
                ('apellido', models.CharField(max_length=10, validators=[localRRHH.models.validate_name])),
                ('salario', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('edad', models.PositiveIntegerField(help_text='Mayor a 21 años', validators=[django.core.validators.MinValueValidator(22)])),
                ('anios_experiencia', models.PositiveIntegerField()),
                ('categoria', models.CharField(choices=[('Culinario', 'Culinario'), ('Medico', 'Medico'), ('Administrativo', 'Administrativo'), ('Mantenimiento', 'Mantenimiento'), ('Entretenimiento', 'Entretenimiento'), ('Personal Extra', 'Personal Extra')], max_length=20)),
                ('puesto', models.CharField(max_length=30)),
                ('pStatus', models.IntegerField(choices=[(1, 'Activo'), (2, 'Inactivo'), (3, 'De baja')], default=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AddField(
            model_name='amonestacion',
            name='personal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='amonestacion', to='localRRHH.personal'),
        ),
    ]
