# Generated by Django 5.2.5 on 2025-09-12 01:37

import django.core.validators
import localRRHH.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localRRHH', '0003_create_pools_and_salaries'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apellidopool',
            options={'verbose_name': 'Apellido Pool', 'verbose_name_plural': 'Apellidos Pool'},
        ),
        migrations.AlterModelOptions(
            name='nombrepool',
            options={'verbose_name': 'Nombre Pool', 'verbose_name_plural': 'Nombres Pool'},
        ),
        migrations.AlterModelOptions(
            name='salariooption',
            options={'verbose_name': 'Salario Option', 'verbose_name_plural': 'Salarios Option'},
        ),
        migrations.AlterField(
            model_name='apellidopool',
            name='apellido',
            field=models.CharField(max_length=30, validators=[localRRHH.models.validate_name]),
        ),
        migrations.AlterField(
            model_name='apellidopool',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='nombrepool',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='nombrepool',
            name='nombre',
            field=models.CharField(max_length=30, validators=[localRRHH.models.validate_name]),
        ),
        migrations.AlterField(
            model_name='personal',
            name='edad',
            field=models.PositiveIntegerField(help_text='Mayor o igual 21 años', validators=[django.core.validators.MinValueValidator(21)]),
        ),
        migrations.AlterField(
            model_name='personal',
            name='salario',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999999)]),
        ),
        migrations.AlterField(
            model_name='salariooption',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
