# Generated by Django 5.2.5 on 2025-09-13 00:12

from django.db import migrations, models

def forwards(apps, schema_editor):
    """Copiar datos desde tablas antiguas a MainPool antes de eliminar tablas."""
    MainPool = apps.get_model('localRRHH', 'MainPool')
    conn = schema_editor.connection
    cursor = conn.cursor()
    try:
        # nombres
        cursor.execute("SELECT nombre FROM localRRHH_nombrepool")
        rows = cursor.fetchall()
        for (nombre,) in rows:
            if nombre is not None:
                MainPool.objects.create(tipo='nombre', valor=nombre)
    except Exception:
        # tabla puede no existir, ignorar
        pass
    try:
        cursor.execute("SELECT apellido FROM localRRHH_apellidopool")
        rows = cursor.fetchall()
        for (apellido,) in rows:
            if apellido is not None:
                MainPool.objects.create(tipo='apellido', valor=apellido)
    except Exception:
        pass
    try:
        cursor.execute("SELECT salario FROM localRRHH_salariooption")
        rows = cursor.fetchall()
        for (salario,) in rows:
            if salario is not None:
                MainPool.objects.create(tipo='salario', valor=str(salario))
    except Exception:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('localRRHH', '0006_alter_apellidopool_options_alter_nombrepool_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('nombre', 'Nombre'), ('apellido', 'Apellido'), ('salario', 'Salario')], max_length=10)),
                ('valor', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Main Pool',
                'verbose_name_plural': 'Main Pools',
            },
        ),
        migrations.RunPython(forwards, reverse_code=migrations.RunPython.noop),
        migrations.DeleteModel(
            name='ApellidoPool',
        ),
        migrations.DeleteModel(
            name='NombrePool',
        ),
        migrations.DeleteModel(
            name='SalarioOption',
        ),
        migrations.AddIndex(
            model_name='mainpool',
            index=models.Index(fields=['tipo', 'valor'], name='localRRHH_m_tipo_ba1acf_idx'),
        ),
    ]
