# Generated by Django 5.2.5 on 2025-09-13 00:28

from django.db import migrations, models


def forwards_copy_amonestacion(apps, schema_editor):
    """Copiar datos desde el modelo histórico Amonestacion hacia Personal usando el ORM.

    Usamos `apps.get_model` para obtener las versiones históricas de los modelos
    en el estado de migración actual y así evitar dependencias del código actual.
    """
    Amonestacion = apps.get_model('localRRHH', 'Amonestacion')
    Personal = apps.get_model('localRRHH', 'Personal')

    # Si no existe el modelo (raro), salir silenciosamente
    if Amonestacion is None:
        return

    for amon in Amonestacion.objects.all():
        try:
            Personal.objects.filter(id=amon.personal_id).update(
                amon_estado=amon.estado if hasattr(amon, 'estado') else False,
                amon_detalle=amon.detalle if hasattr(amon, 'detalle') else None,
            )
        except Exception:
            # Evitar que una fila concreta detenga toda la migración; continuar
            continue


def reverse_nop(apps, schema_editor):
    # No revertimos la copia automáticamente
    return


class Migration(migrations.Migration):

    dependencies = [
        ('localRRHH', '0007_mainpool_delete_apellidopool_delete_nombrepool_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='amon_detalle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='personal',
            name='amon_estado',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(forwards_copy_amonestacion, reverse_nop),
        migrations.DeleteModel(
            name='Amonestacion',
        ),
    ]
