# Generated by Django 4.2.7 on 2025-09-02 04:54

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0009_alter_asignacionpersonal_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventarioproducto',
            name='cantidad_requerida',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='inventarioproducto',
            name='stock_actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='inventarioproducto',
            name='stock_minimo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='personal',
            name='horas_turno',
            field=models.DecimalField(decimal_places=1, default=Decimal('8.0'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.5')), django.core.validators.MaxValueValidator(Decimal('12'))]),
        ),
        migrations.AlterField(
            model_name='tareamantenimiento',
            name='tiempo_estimado_horas',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.5')), django.core.validators.MaxValueValidator(Decimal('24'))]),
        ),
    ]
