# Generated by Django 4.2.7 on 2025-09-05 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0010_agregar_validaciones_completas'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareamantenimiento',
            name='descripcion_solicitud',
            field=models.TextField(blank=True, help_text='Descripción específica de la solicitud del módulo'),
        ),
        migrations.AddField(
            model_name='tareamantenimiento',
            name='es_solicitud_externa',
            field=models.BooleanField(default=False, help_text='Indica si fue solicitado por otro módulo'),
        ),
        migrations.AddField(
            model_name='tareamantenimiento',
            name='modulo_solicitante',
            field=models.CharField(blank=True, choices=[('mantenimiento', 'Mantenimiento'), ('servicios_medicos', 'Servicios Médicos'), ('almacen', 'Almacén'), ('recursos_humanos', 'Recursos Humanos'), ('ventas', 'Ventas'), ('reservas', 'Reservas'), ('restaurante', 'Restaurante'), ('bares', 'Bares'), ('entretenimiento', 'Entretenimiento'), ('compras', 'Compras')], help_text='Módulo que solicitó el mantenimiento', max_length=30, null=True),
        ),
    ]
