# Generated by Django 4.2.7 on 2025-09-05 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0011_tareamantenimiento_descripcion_solicitud_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tareamantenimiento',
            name='descripcion_solicitud',
        ),
        migrations.AddField(
            model_name='tareamantenimiento',
            name='solicitud_original',
            field=models.TextField(blank=True, help_text='Descripción original de la solicitud del módulo'),
        ),
    ]
