# Generated by Django 4.2.7 on 2025-09-05 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mantenimiento', '0012_remove_tareamantenimiento_descripcion_solicitud_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tareamantenimiento',
            name='es_solicitud_externa',
        ),
        migrations.RemoveField(
            model_name='tareamantenimiento',
            name='modulo_solicitante',
        ),
        migrations.RemoveField(
            model_name='tareamantenimiento',
            name='solicitud_original',
        ),
        migrations.CreateModel(
            name='SolicitudMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título descriptivo de la solicitud', max_length=200)),
                ('descripcion', models.TextField(help_text='Descripción detallada del problema o necesidad')),
                ('tipo', models.CharField(choices=[('preventivo', 'Mantenimiento Preventivo'), ('correctivo', 'Mantenimiento Correctivo')], max_length=20)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica'), ('emergencia', 'Emergencia Crítica')], default='media', max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En Revisión'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('en_progreso', 'En Progreso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('modulo_solicitante', models.CharField(choices=[('mantenimiento', 'Mantenimiento'), ('servicios_medicos', 'Servicios Médicos'), ('almacen', 'Almacén'), ('recursos_humanos', 'Recursos Humanos'), ('ventas', 'Ventas'), ('reservas', 'Reservas'), ('restaurante', 'Restaurante'), ('bares', 'Bares'), ('entretenimiento', 'Entretenimiento'), ('compras', 'Compras')], max_length=30)),
                ('ubicacion_solicitud', models.CharField(help_text='Ubicación específica donde se necesita el mantenimiento', max_length=100)),
                ('equipo_afectado', models.CharField(blank=True, help_text='Equipo o área específica que necesita mantenimiento', max_length=200)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_programada', models.DateTimeField(blank=True, help_text='Fecha programada para realizar el mantenimiento', null=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales del personal de mantenimiento')),
                ('materiales_necesarios', models.TextField(blank=True, help_text='Materiales o herramientas necesarias')),
                ('tiempo_estimado', models.IntegerField(blank=True, help_text='Tiempo estimado en minutos', null=True)),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_asignadas', to=settings.AUTH_USER_MODEL)),
                ('crucero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.crucero')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_revisadas', to=settings.AUTH_USER_MODEL)),
                ('solicitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_realizadas', to=settings.AUTH_USER_MODEL)),
                ('tarea_mantenimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitud_origen', to='mantenimiento.tareamantenimiento')),
                ('tipo_crucero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.tipocrucero')),
            ],
            options={
                'verbose_name': 'Solicitud de Mantenimiento',
                'verbose_name_plural': 'Solicitudes de Mantenimiento',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
