# Generated by Django 4.2.7 on 2025-09-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0013_remove_tareamantenimiento_es_solicitud_externa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareamantenimiento',
            name='modulo_origen',
            field=models.CharField(blank=True, help_text='Módulo desde el cual se creó la tarea', max_length=50),
        ),
        migrations.AddField(
            model_name='tareamantenimiento',
            name='origen_url',
            field=models.URLField(blank=True, help_text='URL de origen de la tarea'),
        ),
    ]
