# Generated by Django 5.2.4 on 2025-09-09 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Ingrediente')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio por Unidad')),
                ('unidad', models.CharField(choices=[('kg', 'Kilogramo'), ('g', 'Gramo'), ('l', 'Litro'), ('ml', 'Mililitro'), ('unidad', 'Unidad'), ('taza', 'Taza'), ('cucharada', 'Cucharada'), ('cucharadita', 'Cucharadita')], max_length=20, verbose_name='Unidad de Medida')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('stock_disponible', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Stock Disponible')),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Stock Mínimo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Ingrediente',
                'verbose_name_plural': 'Ingredientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='restaurante',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='ancho',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Ancho (metros)'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='area_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Área Total (m²)'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción del Restaurante'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='horario_apertura',
            field=models.TimeField(blank=True, null=True, verbose_name='Horario de Apertura'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='horario_cierre',
            field=models.TimeField(blank=True, null=True, verbose_name='Horario de Cierre'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='largo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Largo (metros)'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ubicación en el Crucero'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('executive', 'Chef Ejecutivo'), ('chef-partie', 'Jefe de estación'), ('maitre-d', 'Jefe de comedor'), ('bartender', 'Bartender'), ('pastelero', 'Pastelero'), ('cocinero', 'Cocinero'), ('auxiliar', 'Auxiliares de cocina'), ('mesero', 'Mesero'), ('jefe-mesero', 'Jefe de meseros')], max_length=20, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='type',
            field=models.CharField(choices=[('buffet', 'Buffet'), ('principal', 'Restaurante Principal'), ('tematico', 'Restaurante Temático'), ('roomservice', 'Room Service')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Menú')),
                ('tipo', models.CharField(choices=[('desayuno', 'Desayuno'), ('almuerzo', 'Almuerzo'), ('cena', 'Cena'), ('snack', 'Snack'), ('especial', 'Especial')], max_length=20, verbose_name='Tipo de Menú')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('precio_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Total')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurante', verbose_name='Restaurante')),
            ],
            options={
                'verbose_name': 'Menú',
                'verbose_name_plural': 'Menús',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Platillo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Platillo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('categoria', models.CharField(choices=[('entrada', 'Entrada'), ('sopa', 'Sopa'), ('ensalada', 'Ensalada'), ('plato_principal', 'Plato Principal'), ('postre', 'Postre'), ('bebida', 'Bebida'), ('acompanamiento', 'Acompañamiento')], max_length=20, verbose_name='Categoría')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('tiempo_preparacion', models.IntegerField(default=0, verbose_name='Tiempo de Preparación (minutos)')),
                ('porciones', models.IntegerField(default=1, verbose_name='Número de Porciones')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platillos', to='restaurant.menu', verbose_name='Menú')),
            ],
            options={
                'verbose_name': 'Platillo',
                'verbose_name_plural': 'Platillos',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='IngredientePlatillo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad')),
                ('unidad', models.CharField(choices=[('kg', 'Kilogramo'), ('g', 'Gramo'), ('l', 'Litro'), ('ml', 'Mililitro'), ('unidad', 'Unidad'), ('taza', 'Taza'), ('cucharada', 'Cucharada'), ('cucharadita', 'Cucharadita')], max_length=20, verbose_name='Unidad')),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.ingrediente', verbose_name='Ingrediente')),
                ('platillo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='restaurant.platillo', verbose_name='Platillo')),
            ],
            options={
                'verbose_name': 'Ingrediente del Platillo',
                'verbose_name_plural': 'Ingredientes de Platillos',
                'unique_together': {('platillo', 'ingrediente')},
            },
        ),
    ]
