# Generated by Django 5.2.4 on 2025-09-09 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_ingrediente_restaurante_activo_restaurante_ancho_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalRRHH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=10, verbose_name='Apellido')),
                ('salario', models.PositiveIntegerField(verbose_name='Salario')),
                ('edad', models.PositiveIntegerField(verbose_name='Edad')),
                ('anios_experiencia', models.PositiveIntegerField(verbose_name='Años de Experiencia')),
                ('categoria', models.CharField(choices=[('Mantenimiento', 'Mantenimiento'), ('Culinario', 'Culinario'), ('Entretenimiento', 'Entretenimiento'), ('Administrativo', 'Administrativo'), ('Seguridad', 'Seguridad'), ('Limpieza', 'Limpieza')], max_length=20, verbose_name='Categoría')),
                ('puesto', models.CharField(max_length=30, verbose_name='Puesto')),
                ('pStatus', models.IntegerField(choices=[(1, 'Activo'), (2, 'Inactivo'), (3, 'Suspendido')], verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Personal RRHH',
                'verbose_name_plural': 'Personal RRHH',
                'db_table': 'localRRHH_personal_PruebaABorrar',
                'ordering': ['categoria', 'puesto', 'apellido'],
            },
        ),
    ]
