# Generated by Django 5.2.4 on 2025-09-10 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_personalrrhh'),
    ]

    operations = [
        migrations.AddField(
            model_name='platillo',
            name='restaurantes',
            field=models.ManyToManyField(blank=True, related_name='platillos', to='restaurant.restaurante', verbose_name='Restaurantes'),
        ),
    ]
