# Generated by Django 5.2.4 on 2025-09-10 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_platillo_restaurantes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platillo',
            options={'ordering': ['nombre'], 'verbose_name': 'Platillo', 'verbose_name_plural': 'Platillos'},
        ),
        migrations.RemoveField(
            model_name='platillo',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='platillo',
            name='porciones',
        ),
        migrations.RemoveField(
            model_name='platillo',
            name='tiempo_preparacion',
        ),
    ]
