# Generated by Django 5.2.4 on 2025-09-10 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_platillo_options_remove_platillo_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platillo',
            name='restaurantes',
        ),
    ]
