# Generated by Django 5.2.4 on 2025-09-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_remove_platillo_restaurantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='platillo',
            name='restaurantes',
            field=models.ManyToManyField(blank=True, related_name='platillos', to='restaurant.restaurante', verbose_name='Restaurantes'),
        ),
    ]
