# Generated by Django 5.2.4 on 2025-09-10 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_platillo_restaurantes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platillo',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='platillo',
            name='tiempo_preparacion',
        ),
        migrations.RemoveField(
            model_name='platillo',
            name='porciones',
        ),
    ]
