# Generated by Django 5.2.4 on 2025-09-10 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_create_gestion_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComidasPreviu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredientes', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ingredientes')),
                ('tipo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo')),
                ('subtipo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Subtipo')),
                ('clase_alimenticia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Clase Alimenticia')),
                ('detalle', models.TextField(blank=True, null=True, verbose_name='Detalle')),
                ('platos', models.CharField(blank=True, max_length=200, null=True, verbose_name='Platos')),
                ('origen', models.CharField(blank=True, max_length=100, null=True, verbose_name='Origen')),
                ('fuente', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fuente')),
            ],
            options={
                'verbose_name': 'Ingrediente Previu',
                'verbose_name_plural': 'Ingredientes Previu',
                'db_table': 'comidasPreviu',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ingredienteplatillo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
