# Generated by Django 4.2.24 on 2025-09-12 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_comidaspreviu_alter_ingrediente_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=10, unique=True, verbose_name='Código')),
                ('room_number', models.CharField(max_length=10, verbose_name='Habitación')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('cruise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.crucero', verbose_name='Crucero')),
            ],
            options={
                'verbose_name': 'Factura Restaurante',
                'verbose_name_plural': 'Facturas Restaurante',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='type',
            field=models.CharField(choices=[('buffet', 'Buffet'), ('main', 'Main Dining Room'), ('restaurant', 'Restaurante')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='ServiceInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('included', models.BooleanField(default=False, verbose_name='Incluido')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='restaurant.serviceinvoice', verbose_name='Factura')),
                ('platillo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.platillo', verbose_name='Platillo')),
            ],
            options={
                'verbose_name': 'Item Factura',
                'verbose_name_plural': 'Items Factura',
            },
        ),
        migrations.AddField(
            model_name='serviceinvoice',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurante', verbose_name='Restaurante'),
        ),
        migrations.CreateModel(
            name='BuffetBulkRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Cantidad')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('cruise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.crucero', verbose_name='Crucero')),
                ('platillo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.platillo', verbose_name='Platillo')),
                ('restaurant', models.ForeignKey(limit_choices_to={'type': 'buffet'}, on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurante', verbose_name='Buffet')),
            ],
            options={
                'verbose_name': 'Registro Buffet',
                'verbose_name_plural': 'Registros Buffet',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
