# Generated by Django 4.2.24 on 2025-09-12 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_add_cruise_day_to_invoice_and_buffet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_por', models.CharField(max_length=120, verbose_name='Creado por')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('parcial', 'Parcial'), ('entregado', 'Entregado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=12, verbose_name='Estado')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='restaurant.restaurante', verbose_name='Restaurante')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-creado'],
            },
        ),
        migrations.RemoveField(
            model_name='ingrediente',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ingrediente',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='ingrediente',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='ingrediente',
            name='stock_disponible',
        ),
        migrations.RemoveField(
            model_name='ingrediente',
            name='stock_minimo',
        ),
        migrations.RemoveField(
            model_name='platillo',
            name='restaurantes',
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado'),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='subtipo',
            field=models.CharField(choices=[('caducable', 'Caducable'), ('no_caducable', 'No Caducable'), ('refrigerable', 'Refrigerable'), ('no_refrigerable', 'No Refrigerable')], default='no_caducable', max_length=20, verbose_name='Subtipo'),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='tipo',
            field=models.CharField(default='comida', editable=False, max_length=20, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='menu',
            name='is_temporary',
            field=models.BooleanField(default=False, verbose_name='Temporal / Ad-hoc'),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='nombre',
            field=models.CharField(max_length=120, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='unidad',
            field=models.CharField(choices=[('g', 'Gramos'), ('ml', 'Mililitros')], max_length=5, verbose_name='Unidad'),
        ),
        migrations.AlterField(
            model_name='ingredienteplatillo',
            name='unidad',
            field=models.CharField(choices=[('g', 'Gramos'), ('ml', 'Mililitros')], max_length=20, verbose_name='Unidad'),
        ),
        migrations.CreateModel(
            name='WarehouseStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Cantidad Disponible')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('ingrediente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_stock', to='restaurant.ingrediente', verbose_name='Ingrediente')),
            ],
            options={
                'verbose_name': 'Stock Almacén',
                'verbose_name_plural': 'Stocks Almacén',
            },
        ),
        migrations.CreateModel(
            name='RequestLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cant. Solicitada')),
                ('cantidad_aprobada', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Cant. Aprobada')),
                ('cantidad_entregada', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Cant. Entregada')),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.ingrediente', verbose_name='Ingrediente')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='restaurant.request', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Línea Pedido',
                'verbose_name_plural': 'Líneas Pedido',
                'unique_together': {('pedido', 'ingrediente')},
            },
        ),
        migrations.CreateModel(
            name='PantryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Cantidad')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pantry_items', to='restaurant.ingrediente', verbose_name='Ingrediente')),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despensa', to='restaurant.restaurante', verbose_name='Restaurante')),
            ],
            options={
                'verbose_name': 'Item Despensa',
                'verbose_name_plural': 'Items Despensa',
                'unique_together': {('restaurante', 'ingrediente')},
            },
        ),
    ]
