# Generated by Django 4.2.24 on 2025-09-12 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_bootstrap_missing_ingrediente'),
        ('restaurant', '0012_request_remove_ingrediente_created_at_and_more'),
    ]

    operations = [
    ]
