# Generated by Django 4.2.24 on 2025-09-12 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_fix_bootstrap_for_0012'),
        ('restaurant', '0011_fix_bootstrap_for_missing_ingrediente'),
        ('restaurant', '0013_backfill_restaurante_columns'),
        ('restaurant', '0013_merge_20250912_1752'),
    ]

    operations = [
    ]
