# Generated by Django 5.2.6 on 2025-09-11 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0002_empleado_crucero"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="modulosistema",
            options={"ordering": ["codigo"]},
        ),
        migrations.RemoveField(
            model_name="modulosistema",
            name="icono",
        ),
        migrations.RemoveField(
            model_name="modulosistema",
            name="nombre",
        ),
        migrations.RemoveField(
            model_name="modulosistema",
            name="orden",
        ),
        migrations.RemoveField(
            model_name="modulosistema",
            name="url_name",
        ),
        migrations.RemoveField(
            model_name="rol",
            name="permisos",
        ),
    ]
