# Generated by Django 5.2.4 on 2025-09-13 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cruceros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrumentaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=500)),
                ('fecha_adquisicion', models.DateField()),
                ('estado', models.CharField(choices=[('O', 'Operativa'), ('N', 'No operativa')], default='O', max_length=1)),
                ('mantenimiento_programado', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=500)),
                ('fecha_vencimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('especialidad', models.CharField(max_length=100)),
                ('numero_licencia', models.CharField(max_length=50, unique=True)),
                ('telefono', models.CharField(max_length=15)),
                ('correo_electronico', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificacionUrgencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('modulo_origen', models.CharField(help_text='Módulo que envía la notificación', max_length=50)),
                ('solicitante', models.CharField(help_text='Nombre de quien solicita ayuda', max_length=100)),
                ('ubicacion', models.CharField(help_text='Ubicación exacta', max_length=200)),
                ('tipo_urgencia', models.CharField(help_text='Tipo de urgencia', max_length=100)),
                ('descripcion', models.TextField(help_text='Descripción detallada', max_length=1000)),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('A', 'Atendida')], default='P', max_length=1)),
                ('fecha_atendida', models.DateTimeField(blank=True, null=True)),
                ('observaciones_medicas', models.TextField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Notificación de Urgencia',
                'verbose_name_plural': 'Notificaciones de Urgencia',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('nombres', models.CharField(max_length=100)),
                ('primer_apellido', models.CharField(max_length=100)),
                ('segundo_apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('documento_identidad', models.CharField(max_length=20, unique=True)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('fechade_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=15)),
                ('correo_electronico', models.EmailField(max_length=254, unique=True)),
                ('motivo_consulta', models.TextField(max_length=100)),
                ('descripcion_consulta', models.TextField(max_length=500)),
                ('antecedentes_medicos', models.TextField(max_length=500)),
                ('alergias', models.TextField(blank=True, max_length=500, null=True)),
                ('medicamentos_actuales', models.TextField(blank=True, max_length=500, null=True)),
                ('historial_familiar', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('bajo_stockcantidad', models.IntegerField(default=10)),
                ('bajo_stock', models.CharField(choices=[('S', 'Suficiente'), ('B', 'Bajo stock'), ('C', 'Crítico')], default='S', max_length=1)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio_medico.insumo')),
            ],
        ),
        migrations.CreateModel(
            name='PacienteObservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_observacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_alta', models.DateTimeField(blank=True, null=True)),
                ('observacion', models.TextField(max_length=1000)),
                ('tratamiento', models.TextField(blank=True, max_length=1000, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio_medico.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitudmedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camarote', models.CharField(max_length=10)),
                ('razon', models.TextField(blank=True, max_length=500, null=True)),
                ('cantidad', models.IntegerField()),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('E', 'En espera'), ('A', 'Atendido'), ('C', 'Cancelado'), ('F', 'Finalizado')], default='E', max_length=1)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio_medico.insumo')),
            ],
        ),
        migrations.CreateModel(
            name='cuarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Número del cuarto médico', max_length=10)),
                ('estado', models.CharField(choices=[('D', 'Disponible'), ('O', 'Ocupado'), ('M', 'Mantenimiento')], default='D', max_length=1)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('crucero', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cuartos_medicos', to='cruceros.crucero')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicio_medico.paciente')),
            ],
            options={
                'ordering': ['crucero', 'numero'],
                'unique_together': {('crucero', 'numero')},
            },
        ),
    ]
