# Generated by Django 3.2.25 on 2025-09-01 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cuarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('tipo', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('D', 'Disponible'), ('O', 'Ocupado')], default='D', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Instrumentaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=500)),
                ('fecha_adquisicion', models.DateField()),
                ('estado', models.CharField(choices=[('O', 'Operativa'), ('N', 'No operativa')], default='O', max_length=1)),
                ('mantenimiento_programado', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=500)),
                ('fecha_vencimiento', models.DateField()),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('especialidad', models.CharField(max_length=100)),
                ('numero_licencia', models.CharField(max_length=50, unique=True)),
                ('telefono', models.CharField(max_length=15)),
                ('correo_electronico', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('apellido2', models.CharField(blank=True, max_length=100, null=True)),
                ('documento_identidad', models.CharField(max_length=20, unique=True)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('fechade_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=15)),
                ('correo_electronico', models.EmailField(max_length=254, unique=True)),
                ('motivo_consulta', models.TextField(max_length=100)),
                ('descripcion_consulta', models.TextField(max_length=500)),
                ('antecedentes_medicos', models.TextField(max_length=500)),
                ('alergias', models.TextField(blank=True, max_length=500, null=True)),
                ('medicamentos_actuales', models.TextField(blank=True, max_length=500, null=True)),
                ('historial_familiar', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitudmedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camarote', models.CharField(max_length=10)),
                ('razon', models.TextField(blank=True, max_length=500, null=True)),
                ('cantidad', models.IntegerField()),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('E', 'En espera'), ('A', 'Atendido'), ('C', 'Cancelado'), ('F', 'Finalizado')], default='E', max_length=1)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicaciones.insumo')),
            ],
        ),
        migrations.CreateModel(
            name='PacienteObservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_observacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_alta', models.DateTimeField(blank=True, null=True)),
                ('observacion', models.TextField(max_length=1000)),
                ('tratamiento', models.TextField(blank=True, max_length=1000, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicaciones.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicaciones.insumo')),
            ],
        ),
    ]
