# Generated by Django 5.2.5 on 2025-09-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio_medico', '0001_initial'),
    ]

    operations = [
# Placeholder to indicate removal of operations
    ]
