# Generated by Django 5.2.5 on 2025-09-04 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicaciones', '0004_auto_add_cuartos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuarto',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='cuarto',
            name='numero',
            field=models.CharField(choices=[('1', 'Cuarto 1'), ('2', 'Cuarto 2'), ('3', 'Cuarto 3')], editable=False, max_length=1, unique=True),
        ),
    ]
