# Generated by Django 5.2.5 on 2025-09-04 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio_medico', '0002_remove_insumo_cantidad_inventario_bajo_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuarto',
            name='numero',
            field=models.CharField(choices=[('1', 'Cuarto 1'), ('2', 'Cuarto 2'), ('3', 'Cuarto 3')], editable=False, max_length=1, unique=True),
        ),
    ]
