# Generated by Django 5.2.5 on 2025-09-06 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio_medico', '0006_cuarto_paciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionUrgencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_atendida', models.DateTimeField(blank=True, null=True)),
                ('modulo_origen', models.CharField(help_text='Módulo que envía la notificación', max_length=50)),
                ('solicitante', models.CharField(help_text='Nombre de quien solicita ayuda', max_length=100)),
                ('telefono_contacto', models.CharField(blank=True, max_length=15, null=True)),
                ('ubicacion', models.CharField(help_text='Ubicación exacta donde se necesita ayuda', max_length=200)),
                ('tipo_urgencia', models.CharField(help_text='Tipo de urgencia (ej: caída, desmayo, etc.)', max_length=100)),
                ('descripcion', models.TextField(help_text='Descripción detallada de la situación', max_length=1000)),
                ('prioridad', models.CharField(choices=[('B', 'Baja'), ('M', 'Media'), ('A', 'Alta'), ('C', 'Crítica')], default='A', max_length=1)),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('E', 'En camino'), ('A', 'Atendida'), ('C', 'Cancelada')], default='P', max_length=1)),
                ('numero_afectados', models.IntegerField(default=1, help_text='Número de personas afectadas')),
                ('sintomas_observados', models.TextField(blank=True, max_length=500, null=True)),
                ('medidas_tomadas', models.TextField(blank=True, max_length=500, null=True)),
                ('observaciones_medicas', models.TextField(blank=True, max_length=1000, null=True)),
                ('medico_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicio_medico.medico')),
            ],
            options={
                'verbose_name': 'Notificación de Urgencia',
                'verbose_name_plural': 'Notificaciones de Urgencia',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
