# Generated by Django 5.2.5 on 2025-09-06 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio_medico', '0007_notificacionurgencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacionurgencia',
            name='medico_asignado',
        ),
        migrations.RemoveField(
            model_name='notificacionurgencia',
            name='medidas_tomadas',
        ),
        migrations.RemoveField(
            model_name='notificacionurgencia',
            name='numero_afectados',
        ),
        migrations.RemoveField(
            model_name='notificacionurgencia',
            name='prioridad',
        ),
        migrations.RemoveField(
            model_name='notificacionurgencia',
            name='sintomas_observados',
        ),
        migrations.RemoveField(
            model_name='notificacionurgencia',
            name='telefono_contacto',
        ),
        migrations.AlterField(
            model_name='notificacionurgencia',
            name='descripcion',
            field=models.TextField(help_text='Descripción detallada', max_length=1000),
        ),
        migrations.AlterField(
            model_name='notificacionurgencia',
            name='estado',
            field=models.CharField(choices=[('P', 'Pendiente'), ('A', 'Atendida')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='notificacionurgencia',
            name='tipo_urgencia',
            field=models.CharField(help_text='Tipo de urgencia', max_length=100),
        ),
        migrations.AlterField(
            model_name='notificacionurgencia',
            name='ubicacion',
            field=models.CharField(help_text='Ubicación exacta', max_length=200),
        ),
    ]
