# Generated by Django 5.2.5 on 2025-09-06 06:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruceros', '0001_initial'),
        ('servicio_medico', '0008_remove_notificacionurgencia_medico_asignado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuarto',
            options={'ordering': ['crucero', 'numero']},
        ),
        migrations.AddField(
            model_name='cuarto',
            name='crucero',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cuartos_medicos', to='cruceros.crucero'),
        ),
        migrations.AddField(
            model_name='cuarto',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuarto',
            name='fecha_ultima_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cuarto',
            name='estado',
            field=models.CharField(choices=[('D', 'Disponible'), ('O', 'Ocupado'), ('M', 'Mantenimiento')], default='D', max_length=1),
        ),
        migrations.AlterField(
            model_name='cuarto',
            name='numero',
            field=models.CharField(help_text='Número del cuarto médico', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='cuarto',
            unique_together={('crucero', 'numero')},
        ),
    ]
