# Generated by Django 5.2.4 on 2025-09-13 07:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('almacen', '0001_initial'),
        ('cruceros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=60)),
                ('tipo_almacen', models.CharField(max_length=40)),
                ('subtipo_almacen', models.CharField(max_length=40)),
                ('plan', models.CharField(choices=[('gratis', 'All Inclusive'), ('pago', 'Premium')], default='gratis', max_length=10)),
                ('receta', models.TextField(blank=True, default='')),
                ('precio_vta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('instruccion', models.CharField(max_length=800)),
                ('precio_vta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menus', to='bares_snacks.categoria', verbose_name='Categoría')),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('lugarentrega', models.ForeignKey(blank=True, help_text='Instalación física de entrega o consumo (bar, restaurante, etc.)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_entregados', to='cruceros.instalacion')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='bares_snacks.pedidos')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_pedido', to='bares_snacks.productobar')),
            ],
        ),
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('hora_aper', models.DateTimeField(default=django.utils.timezone.now)),
                ('hora_cierre', models.DateTimeField(default=django.utils.timezone.now)),
                ('ubicacion', models.ForeignKey(help_text='Ubicacion del bar dentro del crucero', on_delete=django.db.models.deletion.CASCADE, related_name='bares', to='cruceros.instalacion')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('hora_cierre__gt', models.F('hora_aper'))), name='hcierre_mayorqueapertura')],
            },
        ),
        migrations.CreateModel(
            name='IngredienteReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unidad', models.CharField(blank=True, default='', max_length=20)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usos_bares', to='almacen.producto')),
                ('producto_bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receta_items', to='bares_snacks.productobar')),
            ],
            options={
                'verbose_name': 'Ingrediente de Receta',
                'verbose_name_plural': 'Ingredientes de Receta',
                'unique_together': {('producto_bar', 'ingrediente')},
            },
        ),
    ]
