# Generated by Django 5.2.5 on 2025-09-01 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0001_initial'),
        ('bares_snacks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleados',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='categoria',
        ),
        migrations.AlterField(
            model_name='ingredientesreceta',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.producto'),
        ),
        migrations.RemoveField(
            model_name='ingredientesreceta',
            name='und_medida',
        ),
        migrations.AddField(
            model_name='ingredientesreceta',
            name='medida',
            field=models.CharField(default='unidades', max_length=10),
        ),
        migrations.AlterField(
            model_name='ingredientesreceta',
            name='receta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bares_snacks.menu'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='ingredientes',
            field=models.ManyToManyField(through='bares_snacks.IngredientesReceta', through_fields=('receta', 'producto'), to='almacen.producto'),
        ),
        migrations.DeleteModel(
            name='Cargos',
        ),
        migrations.DeleteModel(
            name='Empleados',
        ),
        migrations.DeleteModel(
            name='Productos',
        ),
    ]
