# Generated by Django 5.2.5 on 2025-09-01 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0002_alter_movimientoalmacen_fecha'),
        ('bares_snacks', '0002_remove_empleados_cargo_remove_pedidos_empleado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientesreceta',
            name='medida',
            field=models.CharField(choices=[('unidades', 'Unidades'), ('gramos', 'Gramos'), ('litros', 'Litros'), ('ml', 'Mililitros'), ('kg', 'Kilogramos')], default='unidades', max_length=10),
        ),
        migrations.AlterField(
            model_name='ingredientesreceta',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_enrecetas', to='almacen.producto'),
        ),
        migrations.AlterField(
            model_name='ingredientesreceta',
            name='receta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes_detalle', to='bares_snacks.menu'),
        ),
    ]
