# Generated by Django 5.2.5 on 2025-09-01 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bares_snacks', '0003_alter_ingredientesreceta_medida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='descripcion',
            field=models.CharField(default='', max_length=100),
        ),
    ]
