# Generated by Django 5.2.4 on 2025-09-13 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bares_snacks', '0021_pedidos_numero_factura'),
        ('creador_embarcaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar',
            name='ubicacion',
            field=models.ForeignKey(help_text='Ubicacion del bar dentro de la embarcación', on_delete=django.db.models.deletion.CASCADE, related_name='bares', to='creador_embarcaciones.locales'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='habitacion',
            field=models.ForeignKey(blank=True, help_text='Habitación destino si el consumo es en camarote', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_servicio', to='creador_embarcaciones.habitaciones'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='lugarentrega',
            field=models.ForeignKey(blank=True, help_text='Local físico de entrega o consumo (bar, restaurante, etc.)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_entregados', to='creador_embarcaciones.locales'),
        ),
    ]
