# Generated by Django 5.2.4 on 2025-09-06 08:58

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaProducto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            (
                                "quimicos_limpieza",
                                "Productos Químicos de Limpieza e Higiene",
                            ),
                            (
                                "consumibles_higiene",
                                "Consumibles de Higiene (Descartables)",
                            ),
                            ("repuestos_criticos", "Repuestos Críticos y Filtros"),
                            ("fluidos_lubricantes", "Fluidos y Lubricantes"),
                            (
                                "herramientas_seguridad",
                                "Herramientas y Equipos de Seguridad",
                            ),
                        ],
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("descripcion", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Categoría de Producto",
                "verbose_name_plural": "Categorías de Productos",
            },
        ),
        migrations.CreateModel(
            name="Crucero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                (
                    "tz_offset_minutos",
                    models.IntegerField(
                        default=-300,
                        help_text="Offset minutos respecto a UTC para 'Hora del Barco'",
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Crucero",
                "verbose_name_plural": "Cruceros",
            },
        ),
        migrations.CreateModel(
            name="Equipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=50, unique=True)),
                ("nombre", models.CharField(max_length=100)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("operativo", "Operativo"),
                            ("mantenimiento", "En Mantenimiento"),
                            ("averiado", "Averiado"),
                            ("fuera_servicio", "Fuera de Servicio"),
                        ],
                        default="operativo",
                        max_length=20,
                    ),
                ),
                ("fecha_instalacion", models.DateField()),
                ("ultima_revision", models.DateTimeField(blank=True, null=True)),
                ("proxima_revision", models.DateTimeField(blank=True, null=True)),
                ("observaciones", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Equipo",
                "verbose_name_plural": "Equipos",
            },
        ),
        migrations.CreateModel(
            name="Personal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("tecnico", "Técnico"),
                            ("supervisor", "Supervisor"),
                            ("operador", "Operador"),
                            ("limpieza", "Limpieza"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("junior", "Junior"),
                            ("medio", "Medio"),
                            ("senior", "Senior"),
                        ],
                        default="medio",
                        max_length=20,
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("disponible", models.BooleanField(default=True)),
                (
                    "horas_turno",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("8.0"),
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.5")),
                            django.core.validators.MaxValueValidator(Decimal("12")),
                        ],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Piscina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "volumen_m3",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=7,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.1"))
                        ],
                    ),
                ),
                ("en_servicio", models.BooleanField(default=True)),
                ("fecha_ultima_limpieza", models.DateField(blank=True, null=True)),
                ("observaciones", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Piscina",
                "verbose_name_plural": "Piscinas",
            },
        ),
        migrations.CreateModel(
            name="PlantillaTarea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                (
                    "tipo_tarea",
                    models.CharField(
                        choices=[
                            ("preventivo", "Mantenimiento Preventivo"),
                            ("correctivo", "Mantenimiento Correctivo"),
                            ("emergencia", "Emergencia"),
                            ("inspeccion", "Inspección"),
                            ("limpieza", "Limpieza"),
                            ("reparacion", "Reparación"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "tiempo_estimado_horas",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1.0"), max_digits=5
                    ),
                ),
                (
                    "prioridad_default",
                    models.CharField(
                        choices=[
                            ("baja", "Baja"),
                            ("media", "Media"),
                            ("alta", "Alta"),
                            ("critica", "Crítica"),
                            ("emergencia", "Emergencia Crítica"),
                        ],
                        default="media",
                        max_length=20,
                    ),
                ),
                (
                    "instrucciones",
                    models.TextField(help_text="Instrucciones paso a paso"),
                ),
                ("activa", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Plantilla de Tarea",
                "verbose_name_plural": "Plantillas de Tareas",
            },
        ),
        migrations.CreateModel(
            name="TipoCrucero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("pequeño", "Crucero Pequeño (2000 pasajeros)"),
                            ("mediano", "Crucero Mediano (4000 pasajeros)"),
                            ("grande", "Crucero Grande (6000 pasajeros)"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("capacidad_pasajeros", models.IntegerField()),
                ("numero_tripulantes", models.IntegerField()),
                ("numero_cubiertas", models.IntegerField()),
            ],
            options={
                "verbose_name": "Tipo de Crucero",
                "verbose_name_plural": "Tipos de Crucero",
            },
        ),
        migrations.CreateModel(
            name="TipoEquipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "requiere_mantenimiento_programado",
                    models.BooleanField(default=True),
                ),
                ("frecuencia_mantenimiento_dias", models.IntegerField(default=30)),
            ],
            options={
                "verbose_name": "Tipo de Equipo",
                "verbose_name_plural": "Tipos de Equipos",
            },
        ),
        migrations.CreateModel(
            name="FiltroGuardado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("filtros", models.JSONField(default=dict)),
                ("publico", models.BooleanField(default=False)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Filtro Guardado",
                "verbose_name_plural": "Filtros Guardados",
            },
        ),
        migrations.CreateModel(
            name="MedicionPiscina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_hora", models.DateTimeField(auto_now_add=True)),
                (
                    "ph",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0")),
                            django.core.validators.MaxValueValidator(Decimal("14.0")),
                        ],
                    ),
                ),
                (
                    "cloro_mg_l",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0")),
                            django.core.validators.MaxValueValidator(Decimal("10.0")),
                        ],
                    ),
                ),
                (
                    "temperatura_c",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "turbidez_ntu",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "presion_filtro_bar",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "estado_filtro",
                    models.CharField(
                        choices=[
                            ("ok", "OK"),
                            ("retrolavado", "Requiere Retrolavado"),
                            ("mantenimiento", "Mantenimiento Requerido"),
                        ],
                        default="ok",
                        max_length=20,
                    ),
                ),
                ("retrolavado_realizado", models.BooleanField(default=False)),
                ("observaciones", models.TextField(blank=True)),
                (
                    "piscina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mediciones",
                        to="mantenimiento.piscina",
                    ),
                ),
            ],
            options={
                "verbose_name": "Medición de Piscina",
                "verbose_name_plural": "Mediciones de Piscina",
                "ordering": ["-fecha_hora"],
            },
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "unidad",
                    models.CharField(
                        choices=[
                            ("litro", "Litro"),
                            ("kg", "Kilogramo"),
                            ("rollo", "Rollo"),
                            ("paquete", "Paquete"),
                            ("unidad", "Unidad"),
                            ("set", "Set"),
                            ("par", "Par"),
                        ],
                        max_length=20,
                    ),
                ),
                ("descripcion", models.TextField(blank=True)),
                ("notas", models.TextField(blank=True)),
                ("activo", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mantenimiento.categoriaproducto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
            },
        ),
        migrations.CreateModel(
            name="ProductoPlantilla",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad_estimada",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("obligatorio", models.BooleanField(default=True)),
                (
                    "plantilla",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mantenimiento.plantillatarea",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mantenimiento.producto",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="plantillatarea",
            name="productos_necesarios",
            field=models.ManyToManyField(
                blank=True,
                through="mantenimiento.ProductoPlantilla",
                to="mantenimiento.producto",
            ),
        ),
        migrations.CreateModel(
            name="TareaMantenimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("preventivo", "Mantenimiento Preventivo"),
                            ("correctivo", "Mantenimiento Correctivo"),
                            ("emergencia", "Emergencia"),
                            ("inspeccion", "Inspección"),
                            ("limpieza", "Limpieza"),
                            ("reparacion", "Reparación"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "prioridad",
                    models.CharField(
                        choices=[
                            ("baja", "Baja"),
                            ("media", "Media"),
                            ("alta", "Alta"),
                            ("critica", "Crítica"),
                            ("emergencia", "Emergencia Crítica"),
                        ],
                        default="media",
                        max_length=20,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("creada", "Creada"),
                            ("planificada", "Planificada"),
                            ("asignada", "Asignada"),
                            ("en_progreso", "En Progreso"),
                            ("esperando_materiales", "Esperando Materiales"),
                            ("esperando_personal", "Esperando Personal"),
                            ("pausada", "Pausada"),
                            ("revision", "En Revisión"),
                            ("completada", "Completada"),
                            ("cancelada", "Cancelada"),
                            ("rechazada", "Rechazada"),
                        ],
                        default="creada",
                        max_length=25,
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_programada", models.DateTimeField()),
                ("fecha_inicio", models.DateTimeField(blank=True, null=True)),
                ("fecha_completada", models.DateTimeField(blank=True, null=True)),
                (
                    "tiempo_estimado_horas",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.0"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.5")),
                            django.core.validators.MaxValueValidator(Decimal("24")),
                        ],
                    ),
                ),
                (
                    "tiempo_real_horas",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                (
                    "asignado_a",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tareas_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "crucero",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mantenimiento.crucero",
                    ),
                ),
                (
                    "equipo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mantenimiento.equipo",
                    ),
                ),
                (
                    "tipo_crucero",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mantenimiento.tipocrucero",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarea de Mantenimiento",
                "verbose_name_plural": "Tareas de Mantenimiento",
                "ordering": ["fecha_programada", "prioridad"],
            },
        ),
        migrations.CreateModel(
            name="ProductoUtilizado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad_utilizada",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("fecha_utilizacion", models.DateTimeField(auto_now_add=True)),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mantenimiento.producto",
                    ),
                ),
                (
                    "tarea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productos_utilizados",
                        to="mantenimiento.tareamantenimiento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto Utilizado",
                "verbose_name_plural": "Productos Utilizados",
            },
        ),
        migrations.CreateModel(
            name="HistorialMantenimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resultado", models.TextField()),
                ("problemas_encontrados", models.TextField(blank=True)),
                ("recomendaciones", models.TextField(blank=True)),
                (
                    "costo_estimado",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("firma_tecnico", models.CharField(max_length=100)),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "tarea",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mantenimiento.tareamantenimiento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial de Mantenimiento",
                "verbose_name_plural": "Historial de Mantenimientos",
            },
        ),
        migrations.CreateModel(
            name="ChecklistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=300)),
                ("completado", models.BooleanField(default=False)),
                ("fecha_completado", models.DateTimeField(blank=True, null=True)),
                ("orden", models.IntegerField(default=1)),
                ("obligatorio", models.BooleanField(default=True)),
                (
                    "usuario_completado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tarea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist_items",
                        to="mantenimiento.tareamantenimiento",
                    ),
                ),
            ],
            options={
                "ordering": ["orden", "id"],
            },
        ),
        migrations.CreateModel(
            name="CambioEstado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("estado_anterior", models.CharField(max_length=25)),
                ("estado_nuevo", models.CharField(max_length=25)),
                ("fecha_cambio", models.DateTimeField(auto_now_add=True)),
                ("observaciones", models.TextField(blank=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tarea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cambios_estado",
                        to="mantenimiento.tareamantenimiento",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_cambio"],
            },
        ),
        migrations.CreateModel(
            name="AdjuntoTarea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archivo", models.FileField(upload_to="adjuntos_tareas/%Y/%m/")),
                ("nombre", models.CharField(max_length=200)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("imagen", "Imagen"),
                            ("pdf", "PDF"),
                            ("documento", "Documento"),
                            ("otro", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("descripcion", models.TextField(blank=True)),
                ("fecha_subida", models.DateTimeField(auto_now_add=True)),
                (
                    "subido_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tarea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjuntos",
                        to="mantenimiento.tareamantenimiento",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_subida"],
            },
        ),
        migrations.AddField(
            model_name="piscina",
            name="tipo_crucero",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mantenimiento.tipocrucero",
            ),
        ),
        migrations.AddField(
            model_name="crucero",
            name="tipo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="mantenimiento.tipocrucero",
            ),
        ),
        migrations.AddField(
            model_name="plantillatarea",
            name="tipo_equipo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mantenimiento.tipoequipo",
            ),
        ),
        migrations.CreateModel(
            name="MantenimientoRecurrente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                (
                    "frecuencia",
                    models.CharField(
                        choices=[
                            ("diario", "Diario"),
                            ("semanal", "Semanal"),
                            ("quincenal", "Quincenal"),
                            ("mensual", "Mensual"),
                            ("bimestral", "Bimestral"),
                            ("trimestral", "Trimestral"),
                            ("semestral", "Semestral"),
                            ("anual", "Anual"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "dias_adelanto",
                    models.IntegerField(
                        default=0, help_text="Días de anticipación para crear la tarea"
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField(blank=True, null=True)),
                ("ultima_generacion", models.DateTimeField(blank=True, null=True)),
                (
                    "plantilla_tarea",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mantenimiento.plantillatarea",
                    ),
                ),
                (
                    "tipo_crucero",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mantenimiento.tipocrucero",
                    ),
                ),
                (
                    "tipo_equipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mantenimiento.tipoequipo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mantenimiento Recurrente",
                "verbose_name_plural": "Mantenimientos Recurrentes",
            },
        ),
        migrations.AddField(
            model_name="equipo",
            name="tipo_equipo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="mantenimiento.tipoequipo",
            ),
        ),
        migrations.CreateModel(
            name="Ubicacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cubierta",
                    models.IntegerField(
                        help_text="Número de cubierta (1-18)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(18),
                        ],
                    ),
                ),
                (
                    "uso",
                    models.IntegerField(
                        choices=[
                            (0, "Habitaciones - Babor"),
                            (1, "Habitaciones - Estribor"),
                            (2, "Restaurantes"),
                            (3, "Bares/Cafés"),
                            (4, "Almacenes"),
                            (5, "Sitios de entretenimiento"),
                            (6, "Libre para especificar"),
                            (7, "Libre para especificar"),
                            (8, "Libre para especificar"),
                            (9, "Libre para especificar"),
                        ],
                        help_text="Tipo de uso de la ubicación",
                    ),
                ),
                (
                    "identificador",
                    models.CharField(
                        help_text="Identificador único (A-Z)", max_length=1
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        help_text="Número de ubicación (01-99)", max_length=2
                    ),
                ),
                ("descripcion", models.CharField(blank=True, max_length=200)),
                ("activa", models.BooleanField(default=True)),
                (
                    "crucero",
                    models.ForeignKey(
                        blank=True,
                        help_text="Crucero al que pertenece esta ubicación",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mantenimiento.crucero",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ubicación",
                "verbose_name_plural": "Ubicaciones",
                "unique_together": {
                    ("cubierta", "uso", "identificador", "numero", "crucero")
                },
            },
        ),
        migrations.AddField(
            model_name="tareamantenimiento",
            name="ubicacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="mantenimiento.ubicacion",
            ),
        ),
        migrations.CreateModel(
            name="ReporteIncidente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                (
                    "severidad",
                    models.CharField(
                        choices=[
                            ("menor", "Menor"),
                            ("moderada", "Moderada"),
                            ("mayor", "Mayor"),
                            ("critica", "Crítica"),
                        ],
                        max_length=20,
                    ),
                ),
                ("fecha_reporte", models.DateTimeField(auto_now_add=True)),
                ("resuelto", models.BooleanField(default=False)),
                ("fecha_resolucion", models.DateTimeField(blank=True, null=True)),
                (
                    "equipo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="mantenimiento.equipo",
                    ),
                ),
                (
                    "reportado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tarea_generada",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="mantenimiento.tareamantenimiento",
                    ),
                ),
                (
                    "tipo_crucero",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tipo de crucero donde ocurrió el incidente",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mantenimiento.tipocrucero",
                    ),
                ),
                (
                    "ubicacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mantenimiento.ubicacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reporte de Incidente",
                "verbose_name_plural": "Reportes de Incidentes",
                "ordering": ["-fecha_reporte"],
            },
        ),
        migrations.AddField(
            model_name="plantillatarea",
            name="ubicacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mantenimiento.ubicacion",
            ),
        ),
        migrations.AddField(
            model_name="piscina",
            name="ubicacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="mantenimiento.ubicacion",
            ),
        ),
        migrations.AddField(
            model_name="equipo",
            name="ubicacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="mantenimiento.ubicacion",
            ),
        ),
        migrations.CreateModel(
            name="AsignacionPersonal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "horas_asignadas",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.5"))
                        ],
                    ),
                ),
                ("fecha_asignacion", models.DateTimeField(auto_now_add=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("asignado", "Asignado"),
                            ("en_progreso", "En Progreso"),
                            ("completado", "Completado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="asignado",
                        max_length=20,
                    ),
                ),
                (
                    "personal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mantenimiento.personal",
                    ),
                ),
                (
                    "tarea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asignaciones",
                        to="mantenimiento.tareamantenimiento",
                    ),
                ),
            ],
            options={
                "unique_together": {("tarea", "personal")},
            },
        ),
        migrations.CreateModel(
            name="InventarioProducto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad_requerida",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "stock_minimo",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "stock_actual",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("fecha_ultima_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "crucero",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mantenimiento.crucero",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mantenimiento.producto",
                    ),
                ),
                (
                    "tipo_crucero",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mantenimiento.tipocrucero",
                    ),
                ),
                (
                    "ubicacion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="mantenimiento.ubicacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventario de Producto",
                "verbose_name_plural": "Inventario de Productos",
                "unique_together": {("producto", "tipo_crucero", "crucero")},
            },
        ),
    ]
