# Generated by Django 4.2.7 on 2025-09-01 03:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('quimicos_limpieza', 'Productos Químicos de Limpieza e Higiene'), ('consumibles_higiene', 'Consumibles de Higiene (Descartables)'), ('repuestos_criticos', 'Repuestos Críticos y Filtros'), ('fluidos_lubricantes', 'Fluidos y Lubricantes'), ('herramientas_seguridad', 'Herramientas y Equipos de Seguridad')], max_length=30, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Categoría de Producto',
                'verbose_name_plural': 'Categorías de Productos',
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('operativo', 'Operativo'), ('mantenimiento', 'En Mantenimiento'), ('averiado', 'Averiado'), ('fuera_servicio', 'Fuera de Servicio')], default='operativo', max_length=20)),
                ('fecha_instalacion', models.DateField()),
                ('ultima_revision', models.DateTimeField(blank=True, null=True)),
                ('proxima_revision', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('unidad', models.CharField(choices=[('litro', 'Litro'), ('kg', 'Kilogramo'), ('rollo', 'Rollo'), ('paquete', 'Paquete'), ('unidad', 'Unidad'), ('set', 'Set'), ('par', 'Par')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('notas', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.categoriaproducto')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='TipoCrucero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pequeño', 'Crucero Pequeño (2000 pasajeros)'), ('mediano', 'Crucero Mediano (4000 pasajeros)'), ('grande', 'Crucero Grande (6000 pasajeros)')], max_length=20, unique=True)),
                ('capacidad_pasajeros', models.IntegerField()),
                ('numero_tripulantes', models.IntegerField()),
                ('numero_cubiertas', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Tipo de Crucero',
                'verbose_name_plural': 'Tipos de Crucero',
            },
        ),
        migrations.CreateModel(
            name='TipoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('requiere_mantenimiento_programado', models.BooleanField(default=True)),
                ('frecuencia_mantenimiento_dias', models.IntegerField(default=30)),
            ],
            options={
                'verbose_name': 'Tipo de Equipo',
                'verbose_name_plural': 'Tipos de Equipos',
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cubierta', models.IntegerField(help_text='Número de cubierta (1-18)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(18)])),
                ('uso', models.IntegerField(choices=[(0, 'Habitaciones - Babor'), (1, 'Habitaciones - Estribor'), (2, 'Restaurantes'), (3, 'Bares/Cafés'), (4, 'Almacenes'), (5, 'Sitios de entretenimiento'), (6, 'Libre para especificar'), (7, 'Libre para especificar'), (8, 'Libre para especificar'), (9, 'Libre para especificar')], help_text='Tipo de uso de la ubicación')),
                ('identificador', models.CharField(help_text='Identificador único (A-Z)', max_length=1)),
                ('numero', models.CharField(help_text='Número de ubicación (01-99)', max_length=2)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'unique_together': {('cubierta', 'uso', 'identificador', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='TareaMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('preventivo', 'Mantenimiento Preventivo'), ('correctivo', 'Mantenimiento Correctivo'), ('emergencia', 'Emergencia'), ('inspeccion', 'Inspección')], max_length=20)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_programada', models.DateTimeField()),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_completada', models.DateTimeField(blank=True, null=True)),
                ('tiempo_estimado_horas', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('tiempo_real_horas', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_creadas', to=settings.AUTH_USER_MODEL)),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.equipo')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.ubicacion')),
            ],
            options={
                'verbose_name': 'Tarea de Mantenimiento',
                'verbose_name_plural': 'Tareas de Mantenimiento',
                'ordering': ['fecha_programada', 'prioridad'],
            },
        ),
        migrations.CreateModel(
            name='ReporteIncidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('severidad', models.CharField(choices=[('menor', 'Menor'), ('moderada', 'Moderada'), ('mayor', 'Mayor'), ('critica', 'Crítica')], max_length=20)),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('resuelto', models.BooleanField(default=False)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mantenimiento.equipo')),
                ('reportado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tarea_generada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mantenimiento.tareamantenimiento')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.ubicacion')),
            ],
            options={
                'verbose_name': 'Reporte de Incidente',
                'verbose_name_plural': 'Reportes de Incidentes',
                'ordering': ['-fecha_reporte'],
            },
        ),
        migrations.CreateModel(
            name='ProductoUtilizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_utilizada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_utilizacion', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.producto')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_utilizados', to='mantenimiento.tareamantenimiento')),
            ],
            options={
                'verbose_name': 'Producto Utilizado',
                'verbose_name_plural': 'Productos Utilizados',
            },
        ),
        migrations.CreateModel(
            name='HistorialMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.TextField()),
                ('problemas_encontrados', models.TextField(blank=True)),
                ('recomendaciones', models.TextField(blank=True)),
                ('costo_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('firma_tecnico', models.CharField(max_length=100)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('tarea', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.tareamantenimiento')),
            ],
            options={
                'verbose_name': 'Historial de Mantenimiento',
                'verbose_name_plural': 'Historial de Mantenimientos',
            },
        ),
        migrations.AddField(
            model_name='equipo',
            name='tipo_equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.tipoequipo'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.ubicacion'),
        ),
        migrations.CreateModel(
            name='InventarioProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_requerida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.producto')),
                ('tipo_crucero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.tipocrucero')),
                ('ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mantenimiento.ubicacion')),
            ],
            options={
                'verbose_name': 'Inventario de Producto',
                'verbose_name_plural': 'Inventario de Productos',
                'unique_together': {('producto', 'tipo_crucero')},
            },
        ),
    ]
