# Generated by Django 5.2.4 on 2025-09-13 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mantenimiento', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adjuntotarea',
            name='subido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cambioestado',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='usuario_completado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='filtroguardado',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventarioproducto',
            name='crucero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.crucero'),
        ),
        migrations.AddField(
            model_name='asignacionpersonal',
            name='personal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.personal'),
        ),
        migrations.AddField(
            model_name='medicionpiscina',
            name='piscina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediciones', to='mantenimiento.piscina'),
        ),
        migrations.AddField(
            model_name='mantenimientorecurrente',
            name='plantilla_tarea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.plantillatarea'),
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.categoriaproducto'),
        ),
        migrations.AddField(
            model_name='inventarioproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.producto'),
        ),
        migrations.AddField(
            model_name='productoplantilla',
            name='plantilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.plantillatarea'),
        ),
        migrations.AddField(
            model_name='productoplantilla',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.producto'),
        ),
        migrations.AddField(
            model_name='plantillatarea',
            name='productos_necesarios',
            field=models.ManyToManyField(blank=True, through='mantenimiento.ProductoPlantilla', to='mantenimiento.producto'),
        ),
        migrations.AddField(
            model_name='productoutilizado',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.producto'),
        ),
        migrations.AddField(
            model_name='reporteincidente',
            name='equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mantenimiento.equipo'),
        ),
        migrations.AddField(
            model_name='reporteincidente',
            name='reportado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tareamantenimiento',
            name='asignado_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tareamantenimiento',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tareamantenimiento',
            name='crucero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.crucero'),
        ),
        migrations.AddField(
            model_name='tareamantenimiento',
            name='equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.equipo'),
        ),
        migrations.AddField(
            model_name='reporteincidente',
            name='tarea_generada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mantenimiento.tareamantenimiento'),
        ),
        migrations.AddField(
            model_name='productoutilizado',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_utilizados', to='mantenimiento.tareamantenimiento'),
        ),
        migrations.AddField(
            model_name='historialmantenimiento',
            name='tarea',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.tareamantenimiento'),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='mantenimiento.tareamantenimiento'),
        ),
        migrations.AddField(
            model_name='cambioestado',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios_estado', to='mantenimiento.tareamantenimiento'),
        ),
        migrations.AddField(
            model_name='asignacionpersonal',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='mantenimiento.tareamantenimiento'),
        ),
        migrations.AddField(
            model_name='adjuntotarea',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='mantenimiento.tareamantenimiento'),
        ),
        migrations.AddField(
            model_name='tareamantenimiento',
            name='tipo_crucero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.tipocrucero'),
        ),
        migrations.AddField(
            model_name='reporteincidente',
            name='tipo_crucero',
            field=models.ForeignKey(blank=True, help_text='Tipo de crucero donde ocurrió el incidente', null=True, on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.tipocrucero'),
        ),
        migrations.AddField(
            model_name='piscina',
            name='tipo_crucero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mantenimiento.tipocrucero'),
        ),
        migrations.AddField(
            model_name='mantenimientorecurrente',
            name='tipo_crucero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.tipocrucero'),
        ),
        migrations.AddField(
            model_name='inventarioproducto',
            name='tipo_crucero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.tipocrucero'),
        ),
        migrations.AddField(
            model_name='crucero',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mantenimiento.tipocrucero'),
        ),
        migrations.AddField(
            model_name='plantillatarea',
            name='tipo_equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.tipoequipo'),
        ),
        migrations.AddField(
            model_name='mantenimientorecurrente',
            name='tipo_equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.tipoequipo'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='tipo_equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.tipoequipo'),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='crucero',
            field=models.ForeignKey(blank=True, help_text='Crucero al que pertenece esta ubicación', null=True, on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.crucero'),
        ),
        migrations.AddField(
            model_name='tareamantenimiento',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.ubicacion'),
        ),
        migrations.AddField(
            model_name='reporteincidente',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.ubicacion'),
        ),
        migrations.AddField(
            model_name='plantillatarea',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.ubicacion'),
        ),
        migrations.AddField(
            model_name='piscina',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.ubicacion'),
        ),
        migrations.AddField(
            model_name='inventarioproducto',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mantenimiento.ubicacion'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.ubicacion'),
        ),
        migrations.AlterUniqueTogether(
            name='asignacionpersonal',
            unique_together={('tarea', 'personal')},
        ),
        migrations.AlterUniqueTogether(
            name='ubicacion',
            unique_together={('cubierta', 'uso', 'identificador', 'numero', 'crucero')},
        ),
        migrations.AlterUniqueTogether(
            name='inventarioproducto',
            unique_together={('producto', 'tipo_crucero', 'crucero')},
        ),
    ]
