# Generated by Django 4.2.7 on 2025-09-01 04:24

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0002_alter_reporteincidente_reportado_por_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rol', models.CharField(choices=[('tecnico', 'Técnico'), ('supervisor', 'Supervisor'), ('operador', 'Operador'), ('limpieza', 'Limpieza')], max_length=20)),
                ('nivel', models.CharField(choices=[('junior', 'Junior'), ('medio', 'Medio'), ('senior', 'Senior')], default='medio', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('disponible', models.BooleanField(default=True)),
                ('horas_turno', models.DecimalField(decimal_places=1, default=Decimal('8.0'), max_digits=4)),
            ],
        ),
        migrations.AddField(
            model_name='tareamantenimiento',
            name='tipo_crucero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.tipocrucero'),
        ),
        migrations.CreateModel(
            name='AsignacionPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_asignadas', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.5'))])),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('asignado', 'Asignado'), ('en_progreso', 'En Progreso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='asignado', max_length=20)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.personal')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='mantenimiento.tareamantenimiento')),
            ],
        ),
    ]
