# Generated by Django 4.2.7 on 2025-09-01 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mantenimiento', '0006_plantillatarea_reporteincidente_tipo_crucero_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiltroGuardado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('filtros', models.JSONField(default=dict)),
                ('publico', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Filtro Guardado',
                'verbose_name_plural': 'Filtros Guardados',
            },
        ),
    ]
