# Generated by Django 4.2.7 on 2025-09-02 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0007_auto_20250901_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crucero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('tz_offset_minutos', models.IntegerField(default=-300, help_text="Offset minutos respecto a UTC para 'Hora del Barco'")),
                ('activo', models.BooleanField(default=True)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mantenimiento.tipocrucero')),
            ],
            options={
                'verbose_name': 'Crucero',
                'verbose_name_plural': 'Cruceros',
            },
        ),
        migrations.AlterUniqueTogether(
            name='inventarioproducto',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='ubicacion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='inventarioproducto',
            name='crucero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.crucero'),
        ),
        migrations.AddField(
            model_name='tareamantenimiento',
            name='crucero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.crucero'),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='crucero',
            field=models.ForeignKey(blank=True, help_text='Crucero al que pertenece esta ubicación', null=True, on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.crucero'),
        ),
        migrations.AlterUniqueTogether(
            name='inventarioproducto',
            unique_together={('producto', 'tipo_crucero', 'crucero')},
        ),
        migrations.AlterUniqueTogether(
            name='ubicacion',
            unique_together={('cubierta', 'uso', 'identificador', 'numero', 'crucero')},
        ),
    ]
