# Generated by Django 5.2.5 on 2025-09-02 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0008_crucero_alter_inventarioproducto_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asignacionpersonal',
            unique_together={('tarea', 'personal')},
        ),
    ]
